### ISSUE TITLE
Fails to recognise usb

### ISSUE THREAD

**Issue by Lledor** [flathub/md.obsidian.Obsidian#1]
Runs well, but does not recognise usb stick when prompted to open vault from folder. The original AppImage from the https://obsidian.md/ website does without fault, so I know that it is not my computers setup.

**Comment by eropleco** [comment]
By default this flatpak is configured to only have access to files under your home directory. You can adjust this by installing Flatseal and adding these 3 paths like the screenshot below, and restart Obsidian. The changes you make here will stick until you click on "Reset" at the top, so you only need to do this once.
![image](https://user-images.githubusercontent.com/73182853/96653810-8ee99300-136c-11eb-80d7-3916d53ec177.png)

**Comment by joshua-stone** [comment]
bot, build md.obsidian.Obsidian

**Comment by joshua-stone** [comment]
@Lledor A new build has been published. Please run `flatpak update md.obsidian.Obsidian --assumeyes` and restart Obsidian to see if it can access USB storage.
