### ISSUE TITLE
remove access to .ssh as a default

### ISSUE THREAD

**Issue by pcause** [flathub/md.obsidian.Obsidian#112]
The flatpak enables access to ~/.ssh as a default setting.  Since this is a default it cannot be removed.  Many users are concerned about safety of plugins and this clearly open a big whole.  If you remove this, users who need it can add back access using flatseal.

**Comment by joshua-stone** [comment]
This has been discussed before:

https://github.com/flathub/md.obsidian.Obsidian/blob/master/README.md#flatpak-permissions

https://github.com/flathub/md.obsidian.Obsidian/pull/16#issuecomment-1165146010
