### ISSUE TITLE
[Feature Request] Add environment variable to optionally enable auto-scrolling chromium flag.

### ISSUE THREAD

**Issue by CoderRuq** [flathub/md.obsidian.Obsidian#116]
One feature I miss from Windows migrating to Linux is auto-scrolling, where instead of the UNIX standard middle-click-to-paste, one can press and hold middle click and move the mouse much like an emulated joystick to scroll continuously instead of using the scroll wheel. This makes large amounts of scrolling far more ergonomic than manually scrolling or reaching for the side scroll-bar.

Chromium (and thus Electron) supports enabling such behavior on Linux, by enabling a special flag:

```
--enable-blink-features=MiddleClickAutoscroll
```

Source: https://askubuntu.com/questions/28150/chrome-chromium-middle-mouse-button-for-scroll-linux-mac

I tested this, and it works in Obsidian, including the Flatpak. It would be nice to have an override variable  to enable this behavior.

---

On a side note, will Flatpak itself (at some point) allow defining and passing flags to the application? Last I checked they only supported passing environment variables to applications via configuration.

Thanks for this distribution of Obsidian!

**Comment by joshua-stone** [comment]
@CoderRuq You should be able to enable it in the next update:

https://github.com/flathub/md.obsidian.Obsidian#middle-click-auto-scrolling
