### ISSUE TITLE
No longer able to order tabs when enabling Wayland variable

### ISSUE THREAD

**Issue by stone2forge** [flathub/md.obsidian.Obsidian#118]
When setting the `"OBSIDIAN_USE_WAYLAND=0"` variable to 1 on **Flatseal**, I couldn't no longer rearrange my tabs, this issue persists in the latest four updated versions (haven't tried more yet).

[Screencast from 2023-02-12 23-33-40.webm](https://user-images.githubusercontent.com/76193584/218378815-258a9709-41f4-4708-adad-ede7b085da34.webm)

**Comment by joshua-stone** [comment]
@stone2forge This is an upstream issue as far as I can tell as it also impacts the appimage:

```
$ ./Obsidian-1.1.9.AppImage \
    --ozone-platform=wayland
    --enable-features=UseOzonePlatform,WaylandWindowDecorations
```

[Please file with the upstream bug tracker.](https://forum.obsidian.md/tags/c/bug-reports/7/linux)
