### ISSUE TITLE
Language warning in appdata?

### ISSUE THREAD

**Issue by ChildishGiant** [flathub/md.obsidian.Obsidian#12]
Why is the app marked for offensive language?

**Comment by joshua-stone** [comment]
It is just a precaution as this is a re-packaging of a project that's largely outside of my control as a downstream maintainer, so over time there may be language that's categorized as "mild" according to OARS: 

https://hughsie.github.io/oars/generate.html#language

You're welcome to ask the developers what they think is most appropriate! The language warning can be removed if they think there's no need for one.

**Comment by joshua-stone** [comment]
Language warning should be removed now:

https://github.com/flathub/md.obsidian.Obsidian/commit/000c2e0aaa995fa19afe239a853ec74b848d7a3c
