### ISSUE TITLE
Can't sync with git because of missing ksshaskpass

### ISSUE THREAD

**Issue by zalzac** [flathub/md.obsidian.Obsidian#120]
# Description:
When I try to sync notes with git in the Flatpak version of Obsidian, I see an error message about missing `ksshaskpass` and I can't synchronize my vault.

# Steps to Reproduce:
 - Open Obsidian in the Flatpak version.
 - Open the command palete
 - Select `Obsidian Git: Push`
 - Wait for the synchronization result to show.

# Expected Result:
The synchronization process should be successful without any error messages, and the notes should be synced with Git. If necessary, prompt for the keypass.

# Actual Result:
The synchronization process fails, and an error message about the missing ksshaskpass tool appears:

```
ssh_askpass: exec(/usr/bin/ksshaskpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

# Workarounds:
 - AppImage version doesn't have this problem; ksshaskpass launches properly.
 - Adding the key with the `ssh-add` command in terminal allows to sync the notes for the duration of the session.

# System Information:

 - Obsidian Version: 1.1.9
 - Operating System: Fedora Linux 37 (KDE Plasma 5.27.0)
 - Flatpak Version: 1.14.1

**Comment by joshua-stone** [comment]
@zalzac Can you test this build?

**Comment by zalzac** [comment]
@joshua-stone do I have to uninstall my existing version?

**Comment by joshua-stone** [comment]
@zalzac If you installed Obsidian system-wide ( `flatpak --system info md.obsidian.Obsidian` ), then no. Uninstalling Obsidian won't do anything to your user data though unless you include `--delete-data` flag.

You can choose to test this as a user install:

```
$ flatpak install --user https://dl.flathub.org/build-repo/7102/md.obsidian.Obsidian.flatpakref
$ flatpak run --user md.obsidian.Obsidian//test
```

```
$ flatpak install --system https://dl.flathub.org/build-repo/7102/md.obsidian.Obsidian.flatpakref
$ flatpak run --system md.obsidian.Obsidian//test
```

**Comment by cam-rod** [comment]
Can confirm this build works. `flatpak run` needs to be run by the DE's command runner, so that it doesn't try to login from the terminal. On GNOME this is Alt-F2, and KDE uses either Alt-F2 or Alt-Space.

**Comment by joshua-stone** [comment]
@cam-rod If that's the case, then I'll merge this.

**Comment by zalzac** [comment]
Everything works fine now. There's no error about missing binaries, a passphrase prompt shows on the first push, I don't have to type the passphrase again in the same session.

Thanks.

**Comment by joshua-stone** [comment]
Thank you for your feedback! :smile:
