### ISSUE TITLE
Update Flatpak Runtime to org.freedesktop.Platform//21.08

### ISSUE THREAD

**Issue by devurandom** [flathub/md.obsidian.Obsidian#13]
I would like to request updating the Flatpak Runtime to org.freedesktop.Platform//21.08, so I can get rid of the old 20.08 version that only very few Flatpaks still require.

**Comment by joshua-stone** [comment]
This should be resolved now:

https://github.com/flathub/md.obsidian.Obsidian/commit/8fe14e7ad5ffdc45db81adaf1b631fed858f0a5d
