### ISSUE TITLE
Unable to move canvas cards by dragging them to a new location.

### ISSUE THREAD

**Issue by phil31753** [flathub/md.obsidian.Obsidian#133]
Chromebook/Linux with Obsidian installed from Flathub. Chromebook and Obsdian updated to latest version.

Prior to Obsidian 1.1.16 Canvas worked fine but since last update,  I am Unable to move cards on the Obsidian canvas by dragging them to a new location.

There is some discussion of this on the Obsidian forum with suggestions that it is either an X11 or Wayland problem. Officlal position seems to be that Linux is a  "niche configuration".

Have tried using Flatseal to change the window manager exclusively to Wayland but Obsidian won't launch. Works fine under X11.

**Comment by joshua-stone** [comment]
Have you determined whether this is a flatpak issue or an upstream Obsidian issue? You may have to do some workarounds:

https://forum.obsidian.md/t/cannot-move-rearrange-panes-when-running-under-wayland/42377/19?u=jstone

**Comment by phil31753** [comment]
Canvas has worked on the Flatpak install of Obsidian on Chromebook since it was released with no problems. For me, I first became aware of the problem with  Obsidian v1.1.16, others have mentioned v1.1.15. ChromeOS, Flatpak and Obsidian (Flathub) are all updated to the latest version.

For me the Canvas workaround is Windows: ) Pity, as a Chromebook with Obsidian is a nice lightweight environment to sling in a backpack. I could run the Android version but apart from no access to Google Drive, Canvas uses iframe which refuses to render some embedded web pages.

Of course, I can still use Obsidian for everything else, including Obsidian Excalidraw, which is a reasonable alternative to Canvas.

**Comment by joshua-stone** [comment]
Can you check with these other builds (.tar,gz, .AppImage, etc) to confirm whether this is a flatpak issue or a downstream issue?

https://github.com/obsidianmd/obsidian-releases/releases

**Comment by joshua-stone** [comment]
Can you also share log output? We've had an issue before with ChromeOS:

https://github.com/flathub/md.obsidian.Obsidian/issues/99

**Comment by phil31753** [comment]
Just tried setting the options, mentioned in [#99](https://github.com/flathub/md.obsidian.Obsidian/issues/99), using Flatseal and it works.

![image](https://user-images.githubusercontent.com/95326157/227753639-3360c2c8-965e-4102-a3f6-a05813778b2a.png)

A generic Linux icon is displayed on the Shelf (task bar)

![image](https://user-images.githubusercontent.com/95326157/227753812-88302a57-3597-4f3d-ae81-5783c21bd959.png)

Normally I launch Obsidian from the ChromeOS shelf (task bar), but if I run from the console **without setting Wayland**,  I get errors. 

Don't have the knowledge to properly interpret this but it looks like something is not right.

```
$ flatpak run md.obsidian.Obsidian
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
2023-03-26 03:17:26 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
[13:0326/111726.378478:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0326/111726.378550:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-03-26 03:17:26 Checking for update using Github
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
2023-03-26 03:17:26 Success.
2023-03-26 03:17:26 Latest version is 1.1.16
2023-03-26 03:17:26 App is up to date.
[54:0326/111735.852379:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[54:0326/111739.388378:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[54:0326/111739.392633:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Warning: disabling flag --expose_wasm due to conflicting flags
```

**Comment by phil31753** [comment]
FYI forcing Wayland in Flatseal using the options shown below does **not** work and Obsidian **does not load** at all.

![image](https://user-images.githubusercontent.com/95326157/227754113-d0c460e1-b0b9-4fad-b27a-1099f5f53923.png)

**Comment by joshua-stone** [comment]
Can you show the following?

```
$ flatpak permission-reset md.obsidian.Obsidian 
$ flatpak run --command=env md.obsidian.Obsidian | grep wayland
```

**Comment by phil31753** [comment]
I assume you want me to do this with OBSIDIAN_USE_WAYLAND and XDG_SESSION_TYPE **not** set?

![image](https://user-images.githubusercontent.com/95326157/227866916-383058a5-db86-48bd-bc33-8a3ddf4d1dfb.png)

**Comment by phil31753** [comment]
Sorry for the delay become less urgent now I have a workaround.

I got an error when I tried those commands.

![Screenshot 2023-04-02 10 56 04](https://user-images.githubusercontent.com/95326157/229328693-a9a110c7-b4d4-4289-b2ca-87b7e764aac4.png)

**Comment by phil31753** [comment]
Now unable to run Obsidian after  those commands!

**Comment by joshua-stone** [comment]
> Sorry for the delay become less urgent now I have a workaround.
> 
> I got an error when I tried those commands.
> 
> ![Screenshot 2023-04-02 10 56 04](https://user-images.githubusercontent.com/95326157/229328693-a9a110c7-b4d4-4289-b2ca-87b7e764aac4.png)

Flathub will eventually delete test builds after enough time has passed. Try this:

```
$ flatpak permission-reset md.obsidian.Obsidian
$ flatpak install --user https://dl.flathub.org/build-repo/14832/md.obsidian.Obsidian.flatpakref
$ flatpak run --user md.obsidian.Obsidian//test
$ flatpak run --user --env=OBSIDIAN_USE_WAYLAND=1 md.obsidian.Obsidian//test
```

**Comment by phil31753** [comment]
If I install this, how do I remove it after the test? Thanks.

**Comment by joshua-stone** [comment]
> If I install this, how do I remove it after the test? Thanks.

After the test is complete, run this:

```
$ flatpak uninstall --user md.obsidian.Obsidian//test
```

**Comment by phil31753** [comment]
```
flatpak permission-reset md.obsidian.Obsidian
flatpak install --user https://dl.flathub.org/build-repo/14832/md.obsidian.Obsidian.flatpakref
flatpak run --user md.obsidian.Obsidian//test
flatpak run --user --env=OBSIDIAN_USE_WAYLAND=1 md.obsidian.Obsidian//test



md.obsidian.Obsidian permissions:
    ipc                  network              pulseaudio      ssh-auth      wayland      x11      dri
    file access [1]      dbus access [2]      tags [3]

    [1] /media, /mnt, /run/media, home, xdg-run/app/com.discordapp.Discord:create
    [2] org.freedesktop.portal.Fcitx
    [3] proprietary

        ID                                     Branch            Op           Remote                    Download
 1. [✓] md.obsidian.Obsidian.Locale            test              i            obsidian-origin            1.7 kB / 3.3 MB
 2. [✓] md.obsidian.Obsidian                   test              i            obsidian-origin           32.5 MB / 150.4 MB

Warning: Not exporting file md.obsidian.Obsidian.appdata.xml of unsupported type.
Installation complete.
Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --enable-features=UseOzonePlatform,WaylandWindowDecorations
Debug: Additionally, user gave: 
2023-04-06 04:38:29 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings

(obsidian:13): Gtk-WARNING **: 12:38:29.801: Theme parsing error: adapta.css:9587:62: Using one color stop with linear-gradient() is deprecated.

(obsidian:13): Gtk-WARNING **: 12:38:29.802: Theme parsing error: adapta.css:10258:71: Using one color stop with linear-gradient() is deprecated.

(obsidian:13): Gtk-WARNING **: 12:38:29.803: Theme parsing error: adapta.css:11225:65: Using one color stop with linear-gradient() is deprecated.
[13:0406/123829.905141:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0406/123829.905197:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-04-06 04:38:29 Checking for update using Github
2023-04-06 04:38:30 Success.
2023-04-06 04:38:30 Latest version is 1.1.16
2023-04-06 04:38:30 App is up to date.
[61:0406/123830.035056:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is egl, ANGLE is 
Warning: disabling flag --expose_wasm due to conflicting flags
Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --enable-features=UseOzonePlatform,WaylandWindowDecorations
Debug: Additionally, user gave: 
2023-04-06 04:39:27 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings

(obsidian:13): Gtk-WARNING **: 12:39:27.409: Theme parsing error: adapta.css:9587:62: Using one color stop with linear-gradient() is deprecated.

(obsidian:13): Gtk-WARNING **: 12:39:27.409: Theme parsing error: adapta.css:10258:71: Using one color stop with linear-gradient() is deprecated.

(obsidian:13): Gtk-WARNING **: 12:39:27.410: Theme parsing error: adapta.css:11225:65: Using one color stop with linear-gradient() is deprecated.
[13:0406/123927.558148:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0406/123927.558201:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-04-06 04:39:27 Checking for update using Github
2023-04-06 04:39:27 Success.
2023-04-06 04:39:27 Latest version is 1.1.16
2023-04-06 04:39:27 App is up to date.
[62:0406/123927.705724:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is egl, ANGLE is
```

**Comment by joshua-stone** [comment]
It looks like it should be launching under Wayland now. Does it improve your experience?

**Comment by phil31753** [comment]
Yes dragging cards on the canvas works.

I can get the same result by  setting these parameters in Flatseal. That is my preferred work around.

```
XDG_SESSION_TYPE=wayland
OBSIDIAN_USE_WAYLAND=1
```

**Comment by joshua-stone** [comment]
You should be able to remove the test build and update Obsidian to get the latest fix:

```
$ flatpak uninstall --user md.obsidian.Obsidian//test
$ flatpak update md.obsidian.Obsidia
```

**Comment by phil31753** [comment]
Thanks.

**Comment by joshua-stone** [comment]
@phil31753 Thanks!

To clarify, `OBSIDIAN_USE_WAYLAND=1` should be the only variable needed to set in flatseal.  `XDG_SESSION_TYPE=wayland` is usually provided by the desktop environment to tell an application whether it's using `wayland` or `x11`, which the Obsidian launcher script will check. 

https://github.com/flathub/md.obsidian.Obsidian/blob/505f566e810349d9d7dfea66b11486b239ac887e/obsidian.sh#L22

**Comment by phil31753** [comment]
Just updated Obsidian with flatpak update and the problem still exists. Once again, fixed by setting parameters in Flatseal.

**Comment by joshua-stone** [comment]
Can you please show the logs of running without any parameters set, then logs after setting ` OBSIDIAN_USE_WAYLAND=1` ?

**Comment by sammypanda** [comment]
**works for me ChromeOS 111.0.0.0:**
disabled everything X display in flatseal and added launch env OBSIDIAN_USE_WAYLAND *and after added it as an override, as far as I can see everything works (desktop icon starts up after configuring for Wayland with proper icon and then changes over to the generic iconic) 

```
Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --enable-features=UseOzonePlatform,WaylandWindowDecorations
Debug: Additionally, user gave: 
2023-04-25 02:00:35 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings

(obsidian:13): Gtk-WARNING **: 12:00:36.018: Theme parsing error: adapta.css:9587:62: Using one color stop with linear-gradient() is deprecated.

(obsidian:13): Gtk-WARNING **: 12:00:36.028: Theme parsing error: adapta.css:10258:71: Using one color stop with linear-gradient() is deprecated.

(obsidian:13): Gtk-WARNING **: 12:00:36.040: Theme parsing error: adapta.css:11225:65: Using one color stop with linear-gradient() is deprecated.
[13:0425/120036.678108:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0425/120036.678907:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-04-25 02:00:37 Checking for update using Github
[60:0425/120038.028073:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is egl, ANGLE is 
2023-04-25 02:00:38 Success.
2023-04-25 02:00:38 Latest version is 1.1.16
2023-04-25 02:00:38 App is up to date.
```
