### ISSUE TITLE
Can't sync with Git

### ISSUE THREAD

**Issue by blacklightpy** [flathub/md.obsidian.Obsidian#140]
### Description

Error Log:
![image](https://user-images.githubusercontent.com/28739146/232873249-234c52f3-b552-4a67-8cd5-120dadc5d2ce.png)

I've set up gh cli, and also git-credential-manager. Both are not being detected.
After debugging for a long time, I thought this might be due to flatpak sandboxing and I tried the AppImage, which worked right out of the box.

I had tried enabling System Files in Flatseal, Followed by enabling all of them, and also adding /usr/bin to folders accessible. No Luck.

### System Information

```bash session
Distro: OpenSUSE Tumbleweed
DE: Plasma
Flatpak Version: 1.14.4
Obsidian Version: 1.1.16
```

### Sandbox Permissions

```bash session
I just uninstalled it, but the defaults were as they were, and I just toggled all Filesystem paths on, and also added /usr/bin manually, hoping to get /usr/bin/gh.
```

### Logs

```bash session
I removed the flatpak now, I'm sleepy rn.
```

**Comment by blacklightpy** [comment]
I cancelled the OpenSSH askpass thing, because it doesn't matter anyways. It shows that GitHub deprecated password authentication.

**Comment by blacklightpy** [comment]
Nvm I fixed it by changing my remotes to use SSH instead of a credential helper.
But I wasn't aware that a credential manager wouldn't work.. so it was time consuming. Could you inform the users about that somehow?

**Comment by joshua-stone** [comment]
I'm not sure if this necessarily a flatpak-specific bug. Can you confirm that the same issue occurs on other builds?

**Comment by blacklightpy** [comment]
It is a Flatpak only issue. The problem is that Flatpak cannot access git-credential-manager or gh because they are in /usr.
AppImage works right out of the box. So I figured out the right solution is to use SSH (which also meant I had to change the remote which was cloned with HTTPS).

I'm not sure whether this belongs in upstream or here.

**Comment by joshua-stone** [comment]
> It is a Flatpak only issue. The problem is that Flatpak cannot access git-credential-manager or gh because they are in /usr. AppImage works right out of the box. So I figured out the right solution is to use SSH (which also meant I had to change the remote which was cloned with HTTPS).
> 
> I'm not sure whether this belongs in upstream or here.

Does the `gh` binary that comes with the flatpak not work?

https://github.com/flathub/md.obsidian.Obsidian#obsidian-git-plugin-support-for-github-login

**Comment by blacklightpy** [comment]
Oh I didn't see that. I'll have to try it tomorrow.

**Comment by blacklightpy** [comment]
Yes, it worked. But I also had to do `flatpak run --command=gh md.obsidian.Obsidian auth setup-git`.
