### ISSUE TITLE
 The bundled gh overwrites git config to global gitconfig

### ISSUE THREAD

**Issue by blacklightpy** [flathub/md.obsidian.Obsidian#148]
### Description

Only gh is affected. git-credential-manager for example stays intact.

```
jyothish@suse ~> gh auth setup-git
jyothish@suse ~> cat .gitconfig
[credential "https://github.com"]
        helper = 
        helper = !/usr/bin/gh auth git-credential
[credential "https://gist.github.com"]
        helper = 
        helper = !/usr/bin/gh auth git-credential
[credential]
        helper = 
        helper = /usr/local/bin/git-credential-manager
        credentialStore = gpg
[credential "https://dev.azure.com"]
        useHttpPath = true
        
        
jyothish@suse ~> flatpak run --command=gh md.obsidian.Obsidian auth setup-git
jyothish@suse ~> cat .gitconfig
[credential "https://github.com"]
        helper = 
        helper = !/app/bin/gh auth git-credential
[credential "https://gist.github.com"]
        helper = 
        helper = !/app/bin/gh auth git-credential
[credential]
        helper = 
        helper = /usr/local/bin/git-credential-manager
        credentialStore = gpg
[credential "https://dev.azure.com"]
        useHttpPath = true
```

### System Information

```bash session
OpenSUSE Tumbleweed
Obsidian: 1.2.7
Flatpak: 1.14.4
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-config/gtk-4.0;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
OBSIDIAN_DISABLE_GPU_SANDBOX=0
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_USE_WAYLAND=0
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
```

### Logs

```bash session
Doesn't seem necessary here
```

**Comment by joshua-stone** [comment]
Have you determined whether this behavior is intrinsic to gh? This doesn't sound like a flatpak-specific bug.

**Comment by joshua-stone** [comment]
It looks like the only difference is that it sets the gh path to `/app/bin/gh`, which is the correct path from inside the flatpak. Is this the only change?

**Comment by blacklightpy** [comment]
Yes, but I think overwriting it is not the right way to go about it, as that prevents me from using the native gh.

**Comment by joshua-stone** [comment]
This doesn't seem to be bug in Obsidian flatpak per se, as it's only bundling the prebuilt `gh` command and isn't modifying its behavior. `gh` is resolving to an absolute file path which is generally a recommended practice to ensure the same executable is called regardless of how $PATH is defined. For example, it's possible for `git` to resolve to a different path depending on whether it's being called inside flatpak:

```
$ which git
/usr/bin/git
$ flatpak run --command=which md.obsidian.Obsidian git
/app/bin/git 
```

This is however inconvenient when trying to work outside of the sandbox, so you may want to see if editing `.gitconfig` is a valid workaround:

```
[credential "https://github.com"]
        helper = 
        helper = !gh auth git-credential
[credential "https://gist.github.com"]
        helper = 
        helper = !gh auth git-credential
[credential]
        helper = 
        helper = /usr/local/bin/git-credential-manager
        credentialStore = gpg
[credential "https://dev.azure.com"]
        useHttpPath = true
```

[You may want to file an issue upstream as well.](https://github.com/cli/cli/issues)

**Comment by joshua-stone** [comment]
The README has clarified this behavior and how to work around it. I recommend [filing an issue](https://github.com/cli/cli/issues) to make gh more configurable for use cases like this.

**Comment by blacklightpy** [comment]
Yup, it's working for me. But I didn't like the idea of manually editing the file at first. Seems like upstream is the problem here.
