### ISSUE TITLE
Tiny cursor on Wayland with 200% scaling

### ISSUE THREAD

**Issue by flexagoon** [flathub/md.obsidian.Obsidian#154]
### Description

When using Obsidian Flatpak with `OBSIDIAN_USE_WAYLAND=1` and 200% scaling, the cursor becomes tiny (see screenshots). This does not happen with non-Flatpak version of Obsidian, even when launched with `--ozone-platform=wayland --enable-features=UseOzonePlatform,WaylandWindowDecorations`.

![image](https://github.com/flathub/md.obsidian.Obsidian/assets/66178592/c565f2f2-29cb-4140-a70f-f64229559741) ![image](https://github.com/flathub/md.obsidian.Obsidian/assets/66178592/bacfcf02-2d34-4438-a782-ddab43d1f69d)

Judging by the logs (attached below), this seems to be an issue with permissions, although I'm not sure, because giving Obsidian access to D-Bus system bus doesn't fix this.

### System Information

```bash session
- Fedora Workstation 38
- GNOME 44.1
- Flatpak 1.15.4
- Obsidian 1.2.8
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
OBSIDIAN_DISABLE_GPU_SANDBOX=0
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_USE_WAYLAND=1
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
```

### Logs

```bash session
Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --enable-features=UseOzonePlatform,WaylandWindowDecorations
Debug: Additionally, user gave: 
[13:0523/133202.800159:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-05-23 10:32:03 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
[13:0523/133203.337839:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0523/133203.337908:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-05-23 10:32:03 Checking for update using Github
2023-05-23 10:32:03 Success.
2023-05-23 10:32:03 Latest version is 1.2.8
2023-05-23 10:32:03 App is up to date.
```

**Comment by flexagoon** [comment]
@joshua-stone yes, that does seem to help. I tried setting `XCURSOR_PATH` before, but I've probably set it to the wrong value, because it didn't work. The value you provided did work for me.

**Comment by joshua-stone** [comment]
You should be able to get the fix in an update:

```
$ flatpak update md.obsidian.Obsidian
```
