### ISSUE TITLE
A new icon for Obsidian has been released

### ISSUE THREAD

**Issue by voedev** [flathub/md.obsidian.Obsidian#165]
A new icon for Obsidian has been released, see [this blog post](https://obsidian.md/blog/new-obsidian-icon/)

Please, update the Obsidian logo on the Flathub home page: 

![2023-06-03_10-45](https://github.com/flathub/md.obsidian.Obsidian/assets/42519520/8e586dc8-ea04-4946-9311-38e32d585b17)

https://flathub.org/apps/md.obsidian.Obsidian

You can download the new logo [here](https://obsidian.md/blog/new-obsidian-icon/)

Thanks 🙌

**Comment by nphalem** [comment]
They already updated the new logo in last commit (39967372569993c60d69aeedfb027bc1b56d9586) and if you updated to the latest version you should have a new purple logo.

What I am wondering is what file/s should be changed to change the logo icon?
I guess it would obviously be `md.obsidian.Obsidian.png` but on my machine (Linux) there are 6 occurrences of that file.
Do I need to change all 6 of them or just a specific one?

**Comment by joshua-stone** [comment]
There's caching on flathub that's keeping the old icon around and it's largely outside of my control. The fix is to wait until it eventually updates on its own.
