### ISSUE TITLE
Verify Obsidian

### ISSUE THREAD

**Issue by joshua-stone** [flathub/md.obsidian.Obsidian#169]
I believe it should be feasible to initiate the [flathub app verification process](https://docs.flathub.org/docs/for-app-authors/verification) for [Obsidian](https://flathub.org/apps/manage/md.obsidian.Obsidian):

```
Create a page at https://obsidian.md/.well-known/org.flathub.VerifiedApps.txt containing the following token:
62495e89-bb1b-4813-96ea-7aa62afe32b4
If the page already exists, add the token to it.
```

**Comment by lishid** [comment]
Done.

**Comment by joshua-stone** [comment]
Thank you!
