### ISSUE TITLE
Error whilst installing Obsidian

### ISSUE THREAD

**Issue by iSaluki** [flathub/md.obsidian.Obsidian#171]
### Description

I ran `flatpak install md.obsidian.Obsidian` on my Fedora Workstation 38 system, 

And got the following output:

```
Looking for matches…
Required runtime for md.obsidian.Obsidian/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/22.08) found in remote flathub
Do you want to install it? [Y/n]: y

md.obsidian.Obsidian permissions:
    ipc                    network        pulseaudio       ssh-auth
    wayland                x11            dri              file access [1]
    dbus access [2]        tags [3]

    [1] /media, /mnt, /run/media, home,
        xdg-run/app/com.discordapp.Discord:create
    [2] org.freedesktop.portal.Fcitx
    [3] proprietary


        ID                         Branch   Op   Remote   Download
 1. [✗] org.freedesktop.Platform   22.08    i    flathub     80.7 MB / 214.4 MB
 2. [ ] md.obsidian.Obsidian       stable   i    flathub  < 170.6 MB

Error: While pulling runtime/org.freedesktop.Platform/x86_64/22.08 from remote flathub: Writing content object: Need more input
error: Failed to install org.freedesktop.Platform: While pulling runtime/org.freedesktop.Platform/x86_64/22.08 from remote flathub: Writing content object: Need more input


```

I have never previously encountered this kind of error with a flatpak. Other flatpaks are installed on the system without issues.

### System Information

```bash session
Distribution: Fedora Workstation 38
Kernel: 6.3.8-200.fc38.x86_64
Flatpak: 1.15.4
Desktop Environment: GNOME
Window Manager: mutter
Graphics platform: AMD Radeon / Mesa
lspci: https://gist.githubusercontent.com/iSaluki/6697edb6305be9e5b3b3200f1e4d73ed/raw/6911b22b3305d9fd11c3459b8e2c82c3c634a73e/lspci.txt
lscpu: https://gist.githubusercontent.com/iSaluki/b31148c91beec860033bcb11ed81da84/raw/f167e31058c45a0e7cfb26aed9cc3f1bb946f421/lscpu.txt

Additional information on request.
```

### Sandbox Permissions

```bash session
Did not install.
```

### Logs

```bash session
Did not install.
```

**Comment by williamhatcher** [comment]
I am experiencing the same issue but with a different error:
```
Error: While pulling app/md.obsidian.Obsidian/x86_64/stable from remote flathub: Writing content object: Need more input
error: Failed to install md.obsidian.Obsidian: While pulling app/md.obsidian.Obsidian/x86_64/stable from remote flathub: Writing content object: Need more input
```

**Comment by williamhatcher** [comment]
@iSaluki this is not an issue with Obsidian. It is an issue with ostree and Fedora 38.
This fix worked for me from: https://github.com/flatpak/flatpak/issues/5452#issuecomment-1605686112
```bash
sudo dnf downgrade ostree-libs
```

**Comment by RedBearAK** [comment]
For those on Fedora 38, this should be a more effective fix while everyone waits for a fixed version of `ostree-libs` to be in a stable repo. 

```sh
sudo dnf downgrade ostree
sudo dnf install dnf-plugins-extras-versionlock
sudo dnf versionlock exclude ostree-2023.4-1.fc38.x86_64
sudo dnf versionlock exclude ostree-libs-2023.4-1.fc38.x86_64
```

This should revert the buggy version of `ostree-libs` (and `ostree` along with it), and then bypass the buggy version if you happen to do another `dnf update` or try to update from the GUI Software app.

**Comment by iSaluki** [comment]
Thank you for providing this info. May I confirm if ostree is actually used on Workstation as well or only Silverblue/Kiniote?

For some reason I was under the impression it was immutable specific.

**Comment by williamhatcher** [comment]
I am running Workstation and was facing the same issue. @RedBearAK thanks for your solution! I decided to go another route: put `excludepkgs=ostree-libs,ostree` in `/etc/dnf/dnf.conf`. Both work well, however.

**Comment by RedBearAK** [comment]
@williamhatcher 

> I decided to go another route: put excludepkgs=ostree-libs,ostree in /etc/dnf/dnf.conf.

Yeah, that works. I considered it, but that doesn't seem like the best way to go about bypassing this issue, since you'll have to remember to go back later when there is a fixed version of the package and make sure you remove that. It will keep blocking the two packages from being considered for updates forever if you forget it about it. 

The version lock option I suggested should just skip over the "bad" version of the package, but allow anything that doesn't match that version to be installed when you update. 

And once this is all blown over it can be removed like this: 

```sh
sudo dnf versionlock clear
```

**Comment by iSaluki** [comment]
Closing issue, not relevant to Obsidian.
