### ISSUE TITLE
Can't open folder as a vault

### ISSUE THREAD

**Issue by LAC-Tech** [flathub/md.obsidian.Obsidian#184]
### Description

On the startup screen, if I select 'Open folder as vault', my xdg-desktop-portal-gtk dialog opens up. I can select a directory in the gui, but it's not registered by obsidian. It will just close the dialog as if I have selected nothing.

### System Information

```bash session
lewis@lightgrey 
--------------- 
OS: Alpine Linux v3.18 x86_64 
Host: MINIPC PN51-E1 0302 
Kernel: 6.1.42-0-lts 
Uptime: 21 hours, 18 mins 
Packages: 1229 (apk), 22 (flatpak) 
Shell: bash 5.2.15 
Resolution: 2560x1440 
WM: i3 
Theme: Greybird [GTK2/3] 
Icons: hicolor [GTK2/3] 
Terminal: xfce4-terminal
Terminal Font: DroidSansMono Nerd Font 10 
CPU: AMD Ryzen 7 5700U with Radeon Graphics (16) @ 1.800GHz 
GPU: AMD ATI 05:00.0 Lucienne 
Memory: 8054MiB / 31497MiB
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;session-bus;system-bus;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-run/gnupg:ro;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;/home/lewis/code;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
OBSIDIAN_USE_WAYLAND=0
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU_SANDBOX=0
```

### Logs

```bash session
lightgrey:~$ flatpak run md.obsidian.Obsidian
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
2023-08-02 01:58:48 Loading main app package /app/resources/obsidian.asar
2023-08-02 01:58:48 Checking for update using Github
```

**Comment by joshua-stone** [comment]
Is this your first time using the Obsidian flatpak?

This seems to be a recurring issue with portals:

https://github.com/flathub/md.obsidian.Obsidian/issues/152

The error message might be a transient issue that may have to be fixed by restarting.

**Comment by LAC-Tech** [comment]
Not my first time, but if I restart I get:

```
lightgrey:~$ flatpak run md.obsidian.Obsidian
F: Can't get document portal: GDBus.Error:org.freedesktop.portal.Error.Failed: Can't mount path /run/user/1000/doc
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
2023-08-02 22:29:02 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
2023-08-02 22:29:02 Checking for update using Github
2023-08-02 22:29:02 Success.
2023-08-02 22:29:02 Latest version is 1.3.7
2023-08-02 22:29:02 App is up to date.
```

with the same issue unfortunately.

If I run it one more time, back to the original error message.

I'm happy to try any portal you recommend.

**Comment by LAC-Tech** [comment]
Did a bit of research:

https://docs.flatpak.org/en/latest/portals.html

Looks like portals have issues opening directories!? If anyone can recommend any portal (kde, gtk, don't care) that can reliably do this I'll just use that.

**Comment by joshua-stone** [comment]
Portals should have no issues opening directories, and in your case Obsidian already has `/home` access.

Which portals do you have installed?

**Comment by joshua-stone** [comment]
I don't believe this is something within my control as a packager as it seems intrinsic to desktop portals. You may want check if anyone has a similar issue here:

https://github.com/flatpak/xdg-desktop-portal-gtk/issues

**Comment by LAC-Tech** [comment]
First off I appreciate your responses to this. I realise it's a very obscure issue.

To answer your questions: I tried both xdg-desktop-portal-gtk, and xdg-desktop-portal-lxqt. Both had the same issue.

Interestingly I get the exact same error message with other flatpak apps, but some of them are able to open directories.

Are there any runtime dependencies this assumes? Other than dbus, any services that should be running?

**Comment by joshua-stone** [comment]
>Are there any runtime dependencies this assumes? Other than dbus, any services that should be running?

I had followed the Flatpak setup steps here in an Alpine VM, and enabling the specified runtime dependencies seemed to be sufficient:

https://wiki.alpinelinux.org/wiki/Flatpak#Setup_/_Installation

It seems that `fuse3` is needed in order for non-root users to install flatpaks, although it's probably not required for this particular issue.

I think it's also worth noting that there shouldn't be multiple xdg-desktop-portal implementations installed at the same time due to the way they register in a specific order. So you should only have `xdg-desktop-portal-gtk` installed.

Can you whether running the command below gets different results?

```
$ flatpak run --nofilesystem=home md.obsidian.Obsidian 
```

**Comment by joshua-stone** [comment]
Here are the packages I had installed:

```
$ apk info | grep 'flatpak\|xdg-desktop-portal\|dbus\|fuse'
dbus
dbus-daemon-launch-helper
dbus-glib
dbus-libs
dbus-openrc
dbus-x11
flatpak
flatpak-bash-completion
fuse-common
fuse-openrc
fuse3
fuse3-libs
xdg-dbus-proxy
xdg-desktop-portal
xdg-desktop-portal-gtk
```

**Comment by LAC-Tech** [comment]
Ok I installed those packages, nuked my flatpak install from high orbit, and now I can open a directory as a vault.

Once again really appreciate your time in helping me with this, but can confirm - it was a flatpak setup issue that only manifested with some apps.
