### ISSUE TITLE
fedora 38 emoji picker (ihub) not working

### ISSUE THREAD

**Issue by jazzbuck** [flathub/md.obsidian.Obsidian#186]
### Description

Using `super+.` to get to the gnome ihub emoji picker only prints a `.` rather than opening the emoji picker on Fedora 37.

### System Information

```bash session
Fedora 38 (workstation)
Gnome 44.3 / Wayland
Flatpak 1.15.4 
Latest Obsidian
```

**Comment by joshua-stone** [comment]
Are you using Obsidian on Wayland or XWayland?

**Comment by jazzbuck** [comment]
It's using Wayland. The AppImage works for getting access to the emoji picker. I've replicated this on two systems.

**Comment by joshua-stone** [comment]
Have you run the Obsidian AppImage with native Wayland backend too, or is it using XWayland? To ensure that it's using Wayland, you can test with these flags:

```
--ozone-platform=wayland --enable-features=UseOzonePlatform,WaylandWindowDecorations
```

**Comment by jazzbuck** [comment]
Using these options with the AppImage replicates the bug where I am unable to access the emoji picker.

**Comment by jazzbuck** [comment]
Yes they work then

**Comment by joshua-stone** [comment]
That's good to know. It sounds like this more of an upstream issue in the Wayland protocol and Electron implementation, rather than an issue caused by flatpak. Should this issue be closed then?

**Comment by jazzbuck** [comment]
Happy for it to be closed!
