### ISSUE TITLE
Any way to use user fonts?

### ISSUE THREAD

**Issue by foldfree** [flathub/md.obsidian.Obsidian#191]
### Additional feature, program, sandbox permission, etc

I would like to use fonts from my /usr/share/fonts and .local/share/fonts folder but I don't know how.
I enabled the folder availability with flatpak override.
I noticed that my flatpak librewolf (firefox browser fork) has access from system fonts out of the box.

Is that a bug with Electron on Linux, the Obsidian linux build itself or me doing something wrong? 

I would be thankful for your guidance.

**Comment by joshua-stone** [comment]
Can you see if running the command below makes a difference?

```
flatpak run --filesystem=~/.local/share/fonts md.obsidian.Obsidian
```

Worth noting that you'll have to make sure whatever fonts you want are copied into `~/.local/share/fonts`, and symlinking `/usr/share/fonts` isn't guaranteed to work.

You can also add the following for accessing system fonts, however they'll only be visible from `/run/host/fonts` which I'm not sure Obsidian will be able to automatically detect:

```
flatpak run  --filesystem=host --filesystem=~/.local/share/fonts md.obsidian.Obsidian
```

**Comment by tunix** [comment]
I just installed JetBrains Mono into my ~/.local/share/fonts - I checked and verified that this setting is already configured inside Flatseal. But when I start Obsidian, I can't see the font within the listed fonts.
