### ISSUE TITLE
Extremely low resolution after updating to 1.4.x

### ISSUE THREAD

**Issue by xplosionmind** [flathub/md.obsidian.Obsidian#194]
### Description

As the screenshot below shows, the resolution of the application after updating to 1.4.5 is extremely low.

![Screenshot from 2023-09-01 22-15-09](https://github.com/flathub/md.obsidian.Obsidian/assets/42862428/2f154d24-cf46-4ab8-8593-24863accf7bb)

#### Flatseal screenshots

![Screenshot from 2023-09-01 22-16-56](https://github.com/flathub/md.obsidian.Obsidian/assets/42862428/6207f779-11ef-4dd9-a715-0ef0c4b2cd8d)

![Screenshot from 2023-09-01 22-17-18](https://github.com/flathub/md.obsidian.Obsidian/assets/42862428/3d6a500e-c208-4d5f-977d-0214639284d0)
![Screenshot from 2023-09-01 22-17-10](https://github.com/flathub/md.obsidian.Obsidian/assets/42862428/b551e274-15e6-46db-a89a-fe06074acfbe)

![Screenshot from 2023-09-01 22-17-33](https://github.com/flathub/md.obsidian.Obsidian/assets/42862428/6e83f960-6b16-47dc-8a72-9300ce26387d)
![Screenshot from 2023-09-01 22-17-26](https://github.com/flathub/md.obsidian.Obsidian/assets/42862428/ad852e2f-8293-4bf8-8a1a-628b68129703)

### System Information

Fedora Linux 38 (Workstation Edition)
Wayland
GNOME 44.4
Linux 6.4.12-200.fc38.x86_64

### Sandbox Permissions

```bash session
flatpak info --show-permissions md.obsidian.Obsidian
```

### Logs

```bash session
flatpak run md.obsidian.Obsidian

Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --enable-features=UseOzonePlatform,WaylandWindowDecorations --enable-blink-features=MiddleClickAutoscroll
Debug: Additionally, user gave: 
2023-09-01 20:19:10 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
2023-09-01 20:19:11 Checking for update using Github
2023-09-01 20:19:11 Success.
2023-09-01 20:19:11 Latest version is 1.4.5
2023-09-01 20:19:11 App is up to date.
/app/bin/obsidian.sh: line 40:    13 Segmentation fault      (core dumped) zypak-wrapper /app/obsidian $@ ${EXTRA_ARGS[@]}
```

The segmentation fault occurs upon closing, therefore I believe it is unrelated with this bug.

**Comment by joshua-stone** [comment]
@xplosionmind What's your zoom level set to? It looks to be around 120%.

**Comment by xplosionmind** [comment]
> What's your zoom level set to?

It is 100%.

![Screenshot from 2023-09-02 10-56-24](https://github.com/flathub/md.obsidian.Obsidian/assets/42862428/4d74eaf7-1c8d-4639-912c-6cb7e5826c7c)

**Comment by matosjoaops** [comment]
I'm also having this issue, and not just with Obsidian. I think it's an issue with more recent versions of Chromium that occurs when resolution scale is not 100%. I think the 1.4 update may have upgraded the Electron version and that is why the problem is showing up now in Obsidian.

**Comment by joshua-stone** [comment]
@matosjoaops Thank you for tracking down the bug. Can you confirm that this affects all Obsidian builds and not just the flatpak?

**Comment by matosjoaops** [comment]
@joshua-stone Just tried out the AppImage version and the issue is also present when running the app under Wayland

**Comment by joshua-stone** [comment]
@xplosionmind Please file a bug report with the upstream bug tracker since the flatpak is only a downstream build:

https://forum.obsidian.md/c/bug-reports/7

**Comment by xplosionmind** [comment]
[Here](https://forum.obsidian.md/t/extremely-low-resolution-in-obsidian-1-4-x-on-linux-with-wayland/66441 'Extremely low resolution in Obsidian 1.4.x on Linux with Wayland') is the upstream bug report.

Thanks a lot @joshua-stone and @matosjoaops for your help!

**Comment by n0t1** [comment]
Is it possible to rollback to a previous version?

**Comment by joshua-stone** [comment]
Yes, you can pick one of the commits from before https://github.com/flathub/md.obsidian.Obsidian/commit/72cf4b13eb806dc3a4964f29bd8652cdfb881777:

```
$ flatpak remote-info flathub md.obsidian.Obsidian --log
        ID: md.obsidian.Obsidian
       Ref: app/md.obsidian.Obsidian/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 174.4 MB
 Installed: 579.1 MB
   Runtime: org.freedesktop.Platform/x86_64/22.08
       Sdk: org.freedesktop.Sdk/x86_64/22.08

    Commit: 03caff63176c73e7578f760211abfc8d9e001da9579935c552499bd34ef398d0
    Parent: df4ad574288b02356d5318f6d5c1edd1d7d88320a5c08d96472d695cd509bff4
   Subject: Update 4 modules (72cf4b13)
      Date: 2023-08-31 21:49:03 +0000
   History: 

    Commit: df4ad574288b02356d5318f6d5c1edd1d7d88320a5c08d96472d695cd509bff4
   Subject: Update 2 modules (69edc2d6)
      Date: 2023-08-23 02:46:41 +0000

    Commit: 79b6a284ae8bd87777ba4e460b4ac96006ee4c8596c32c673a4a4d3b8715cadf
   Subject: Update 2 modules (5fedc75f)
      Date: 2023-08-21 19:51:05 +0000

    Commit: 1cf4b36cecd08af4f9fa889f060988243fd1309fbc3a18cd84e62e05ebf3ecaa
   Subject: Update git-2.41.0.tar.xz to 2.42.0 (#188) (1280577a)
      Date: 2023-08-21 18:20:02 +0000

    Commit: 2eb20bb32b8bf3b61c149ddc462f2799c42d42982885a585885982218526bb9d
   Subject: Update openssh-9.3p2.tar.gz to 9.4p1 (9ab28e70)
      Date: 2023-08-10 05:56:33 +0000

    Commit: 8536d1fd73bec64df53a5fd9e96927a8261ce5c579f6721b3b292f24ac7f21bf
   Subject: Update 2 modules (241ebb9b)
      Date: 2023-08-07 03:51:49 +0000
<snip>
```

```
$ flatpak update md.obsidian.Obsidian --commit=df4ad574288b02356d5318f6d5c1edd1d7d88320a5c08d96472d695cd509bff4
Looking for updates…


        ID                            Branch          Op         Remote          Download
 1.     md.obsidian.Obsidian          stable          u          flathub         < 173.6 MB

Proceed with these changes to the system installation? [Y/n]: 
```

**Comment by joshua-stone** [comment]
@xplosionmind @n0t1 Can you test this build to see if it addresses the issue?

```
flatpak install --user https://dl.flathub.org/build-repo/46923/md.obsidian.Obsidian.flatpakref
flatpak run --user --env=OBSIDIAN_USE_WAYLAND=1 md.obsidian.Obsidian//test
```

**Comment by matosjoaops** [comment]
@joshua-stone Unfortunately, the issue is still present with that build

**Comment by joshua-stone** [comment]
Can you share log output as well as a screenshot of the zoom settings?

**Comment by matosjoaops** [comment]
@joshua-stone 

Log output:
```
Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations
Debug: Additionally, user gave:
[13:0908/191805.142712:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-09-08 18:18:05 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
[13:0908/191805.558622:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0908/191805.558641:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-09-08 18:18:05 Checking for update using Github
2023-09-08 18:18:05 Success.
2023-09-08 18:18:05 Latest version is 1.4.5
2023-09-08 18:18:05 App is up to date.
```

Zoom settings:
![imagem](https://github.com/flathub/md.obsidian.Obsidian/assets/56487084/1b389b45-c4ae-49ce-bbe8-a1b5e8dc398e)

**Comment by xplosionmind** [comment]
I found a workaround by specifying in Flatseal to use X11 only for this app, and the resolution matches the screen one once again. Unfortunately, the cursor appears to be super tiny, though.

**Comment by joshua-stone** [comment]
Marking as closed since it appears to be an upstream issue, and a change has been merged which should help some users.
