### ISSUE TITLE
After update with "flatpak update" - Obsidian warns after startup that an update is available and .... (see below) 

### ISSUE THREAD

**Issue by mathias73ch** [flathub/md.obsidian.Obsidian#20]
... and a manual installation is required to update to the latest version. As far as I know that is needed on a MacOS-client when the Electron-framework (which is in the same installer) needs an update. 

could it be that the flathub package does not take the new Electron-version into account on which the latest Obsidian-version is based?

regards, Mathias

**Comment by mathias73ch** [comment]
Forgot to mention: used on a Raspberry Pi OS, arm64

**Comment by joshua-stone** [comment]
The aarch64 build should be pulling in a newer version now:

https://github.com/flathub/md.obsidian.Obsidian/commit/b623c6017195d83da0bdd482c527644d8cc52de6
