### ISSUE TITLE
Node Graph does not render nodes properly

### ISSUE THREAD

**Issue by KettLovahr** [flathub/md.obsidian.Obsidian#208]
### Description

While trying to display the node graph, Obsidian only shows the links and titles, but not the nodes themselves. 

![A screenshot of Obsidian's node graph, the nodes themselves are invisible, but the links between them can be seen](https://github.com/flathub/md.obsidian.Obsidian/assets/25535207/caf72e13-530f-4d0d-8514-3626253383f6)

Opening the developer console, the message `PixiJS Error: Could not initialize shader.` is displayed.

![A screenshot of a portion of the developer console showing the error described above as well as hundreds of WebGL errors](https://github.com/flathub/md.obsidian.Obsidian/assets/25535207/ebc817a3-aff2-472d-b55b-7ef50d34f8e7)

This issue seems to be exclusive to the Flatpak version, the AppImage works properly, though I'd rather use the Flatpak for convenience.

Passing the `--disable-gpu` flag makes the nodes render properly, but performance suffers greatly from it.

### System Information

```bash session
openSUSE Tumbleweed
KDE Plasma (Issue present on both Wayland and X11)
Obsidian Version 1.4.14
Flatpak Version 1.15.4
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-run/gnupg:ro;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
OBSIDIAN_USE_WAYLAND=0
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU_SANDBOX=0
```

### Logs

```bash session
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
[12:0929/004944.986195:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-09-29 03:49:45 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
[12:0929/004945.111422:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[12:0929/004945.111466:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-09-29 03:49:45 Checking for update using Github
2023-09-29 03:49:45 Success.
2023-09-29 03:49:45 Latest version is 1.4.14
2023-09-29 03:49:45 App is up to date.
```

**Comment by KettLovahr** [comment]
Alright, so when `OBSIDIAN_USE_WAYLAND` is set to 0, it doesn't render nodes on _either X11 or Wayland_, but when it's set to 1, it works fine on Wayland **only**.

As small as it is, I guess that's one more reason to stick with Wayland. :P

**Comment by KettLovahr** [comment]
My GPU is an RX 6600, and I'm using the radeon drivers.

**Comment by joshua-stone** [comment]
Does the issue persist after updating Obsidian?

**Comment by KettLovahr** [comment]
Nope! Fixed on X11 too after updating, everything seems fine now.
