### ISSUE TITLE
text, icons, and ui widgets are invisible

### ISSUE THREAD

**Issue by salarua** [flathub/md.obsidian.Obsidian#214]
### Description

When opening Obsidian, only the underlines of links and tab shadows appear.

![image](https://github.com/flathub/md.obsidian.Obsidian/assets/104225819/dc5df8df-4100-4cdb-b49c-7c4034f0951c)

### System Information

```bash session
Linux distro: Fedora Linux 38
Desktop environment: GNOME 44
Flatpak 1.15.4
Version 1.4.14
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-run/gnupg:ro;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;xdg-config/gtk-3.0;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
OBSIDIAN_USE_WAYLAND=0
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU_SANDBOX=0
```

### Logs

[obsidian_log.txt](https://github.com/flathub/md.obsidian.Obsidian/files/12821626/obsidian_log.txt)

**Comment by jw580755** [comment]
Same here.

Linux distro: Fedora Linux 38
Desktop environment: GNOME 45
Flatpak 1.15.4
Version 1.4.14

**Comment by AlexaBennett** [comment]
Same here.

Linux distro: Fedora Linux 38 (Workstation Edition)
Uninstalled and reinstalled using the "Software" GUI.

**Comment by joshua-stone** [comment]
I'm encountering a similar issue:

```
[70:1005/193357.338260:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in half4 color;flat out half4 vcolor_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
flat in half4 vcolor_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in mediump vec4 color;
flat out mediump vec4 vcolor_S0;
void main() {
    vcolor_S0 = color;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
flat in mediump vec4 vcolor_S0;
void main() {
    mediump vec4 outputColor_S0;
    outputColor_S0 = vcolor_S0;
    {
        sk_FragColor = outputColor_S0;
    }
}


Errors:
link failed but did not provide an info log
```

![image](https://github.com/flathub/md.obsidian.Obsidian/assets/8183967/cfc65a60-a22f-439e-af9d-1294e8d60699)

This is almost certainly an issue with the latest Freedesktop runtime update because Obsidian was working fine until updating the runtime:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases/freedesktop-sdk-22.08.16

```
$ flatpak info org.freedesktop.Platform//22.08

Freedesktop Platform - Shared libraries

          ID: org.freedesktop.Platform
         Ref: runtime/org.freedesktop.Platform/x86_64/22.08
        Arch: x86_64
      Branch: 22.08
     Version: 22.08.16
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 568.7 MB

      Commit: 9d00a8cd4b3ea5f83c871a060303d5f84330dc674d2bc555629aa808ef11c2e2
      Parent: 5644f61a158b5437141ba41ecba1e71ccf2d29caaaa24ae04251d2f7fcd9daeb
     Subject: Export org.freedesktop.Platform
        Date: 2023-10-05 15:41:39 +0000
```

@salarua @jw580755 @AlexaBennett Can you see if disabling GPU acceleration works?

```
$ flatpak run --env=OBSIDIAN_DISABLE_GPU=1 md.obsidian.Obsidian
```

**Comment by joshua-stone** [comment]
I've filed a bug in the Freedeskop runtime's issue tracker, as this issue appears to originate from the runtime:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1655

**Comment by joshua-stone** [comment]
It appears that removing the `mesa_shader_cache` fixed the issue for me:

```
$ rm -rf /.var/app/md.obsidian.Obsidian/cache/mesa_shader_cache/
$ flatpak run md.obsidian.Obsidian
Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations
Debug: Additionally, user gave: 
[13:1005/211933.928649:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-10-06 01:19:34 Loading main app package /app/resources/obsidian.asar
Updates disabled.
LaunchProcess: failed to execvp:
xdg-settings
[13:1005/211934.145778:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:1005/211934.145821:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

Can anyone confirm that this works for them as well?

**Comment by salarua** [comment]
I cannot confirm. I tried removing the `mesa_shader_cache` like you did and got the same errors when I ran it next.

**Comment by bpauw** [comment]
Disabling GPU acceleration worked for me to get Obsidian working.

Canvas feels like it's moving through molasses,  but at least everything is functional again haha.

*disable GPU acceleration*

```sh
flatpak override --user --env=OBSIDIAN_DISABLE_GPU=1 md.obsidian.Obsidian
```

*to re-enable GPU acceleration (after this is fixed upstream)*

```sh
flatpak override --user --unset-env=OBSIDIAN_DISABLE_GPU md.obsidian.Obsidian
```

**Comment by bpauw** [comment]
> It appears that removing the `mesa_shader_cache` fixed the issue for me:
> 
> ```
> $ rm -rf /.var/app/md.obsidian.Obsidian/cache/mesa_shader_cache/
> $ flatpak run md.obsidian.Obsidian
> Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations
> Debug: Additionally, user gave: 
> [13:1005/211933.928649:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> 2023-10-06 01:19:34 Loading main app package /app/resources/obsidian.asar
> Updates disabled.
> LaunchProcess: failed to execvp:
> xdg-settings
> [13:1005/211934.145778:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [13:1005/211934.145821:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> ```
> 
> Can anyone confirm that this works for them as well?

@joshua-stone this did not resolve the issue for me. I'm running Obsidian on X, not Wayland. Not sure if that makes a difference.

**Comment by gbottazzoli** [comment]
this works ! Thanks a lot. 

flatpak override --user --env=OBSIDIAN_DISABLE_GPU=1 md.obsidian.Obsidian

**Comment by Libric0** [comment]
Can confirm as well. But yeah graph view is a lot slower. Seems to be the underlying problem though

> this works ! Thanks a lot.
> 
> flatpak override --user --env=OBSIDIAN_DISABLE_GPU=1 md.obsidian.Obsidian

**Comment by joshua-stone** [comment]
Can anyone see if rolling back a runtime update helps?

```
sudo flatpak update org.freedesktop.Platform.GL.default//22.08       --commit=60292a56526a549372343d417b6db843890d917882e1e64bee9fc4e7f187946f
sudo flatpak update org.freedesktop.Platform.GL.default//22.08-extra --commit=b280745e536d10781419e9f6f98e65d48839672270193feedc59d7df3f5c7dea
sudo flatpak update org.freedesktop.Platform.Locale//22.08           --commit=ceb68067dcf1f6a93ae0d920dae301ff752c4f27e1718273c97fc2017cf5c35f
sudo flatpak update org.freedesktop.Platform//22.08                  --commit=5644f61a158b5437141ba41ecba1e71ccf2d29caaaa24ae04251d2f7fcd9daeb
```

**Comment by joshua-stone** [comment]
@bpauw It looks like there's another cache folder. Does this help?

```
$ rm -rf /.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
```

**Comment by bpauw** [comment]
> @bpauw It looks like there's another cache folder. Does this help?
> 
> ```
> $ rm -rf /.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
> ```

@joshua-stone yes, this worked!!! Problem solved!!! Thank you!

To recap, the problem has been resolved for me by deleting these two directories:

```sh
~/.var/app/md.obsidian.Obsidian/cache
~/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
```

**Comment by habeasdata404** [comment]
> Thanks for the suggestion @joshua-stone, disabling GPU acceleration worked for me to get Obsidian working.
> 
> Canvas feels like it's moving through molasses, but at least everything is functional again haha.
> 
> _disable GPU acceleration_
> 
> ```shell
> flatpak override --user --env=OBSIDIAN_DISABLE_GPU=1 md.obsidian.Obsidian
> ```
> 
> _to re-enable GPU acceleration (after this is fixed upstream)_
> 
> ```shell
> flatpak override --user --unset-env=OBSIDIAN_DISABLE_GPU md.obsidian.Obsidian
> ```

@joshua-stone, this fix (override) worked for me. I didn't delete any folders.

## System information

```
- Ubuntu 22.04.3 LTS x86_64 
- Flatpak 1.12.7
- Obsidian 1.4.14 (installer version 1.4.14)
- Desktop environment: GNOME 42.9
- X11
```

**Comment by AlexaBennett** [comment]
> ```shell
> ~/.var/app/md.obsidian.Obsidian/cache
> ~/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
> ```

This has resolved the issue for me as well. Thank you, @bpauw and @joshua-stone, for figuring this out so quickly.

**Comment by jw580755** [comment]
~/.var/app/md.obsidian.Obsidian/cache
~/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache

That was the solution. Many thanks.

**Comment by joshua-stone** [comment]
The latest update should have this fix in place:

```
$ flatpak run md.obsidian.Obsidian
Deleting cache directory: /var/home/jstone/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
```
