### ISSUE TITLE
Add a PSA for Pinch Zoom support by forcing Wayland on Wayland sessions

### ISSUE THREAD

**Issue by Moota-0** [flathub/md.obsidian.Obsidian#242]
### Additional feature, program, sandbox permission, etc

It would be great to add a PSA somewhere to indicate that in order to be able to pinch for zooming with a touchpad on a Wayland session you have to force the use of Wayland, or maybe detect the session's windowing system and use the respective windowing system to reduce bugs.

**Comment by joshua-stone** [comment]
@Moota-0 Would you like to a section in the [README](https://github.com/flathub/md.obsidian.Obsidian#wayland-support) for Wayland-specific features?

**Comment by joshua-stone** [comment]
The README and metainfo have been updated to include this PSA.
