### ISSUE TITLE
Add compatibility with discord Rich Precense 

### ISSUE THREAD

**Issue by Obito1903** [flathub/md.obsidian.Obsidian#26]
There is a plugin in obsidian that allow you to share your activity with discord using the Rich presence feature, but flatpak blocks it by default.

It would be nice to allow this feature to work in the flatpak version of Obsidian.

Thanks.

Details on RPC for discord flatpak : https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)
Obsidian plugin : https://github.com/lukeleppan/obsidian-discordrpc

**Comment by soredake** [comment]
Example of doing this from yuzu flatpak:
https://github.com/flathub/org.yuzu_emu.yuzu/blob/6d245eaf894daf55b72475f2a824d46d7d7cc95b/org.yuzu_emu.yuzu.json#L15
https://github.com/flathub/org.yuzu_emu.yuzu/blob/6d245eaf894daf55b72475f2a824d46d7d7cc95b/yuzu-launcher.sh#L17-L20

**Comment by joshua-stone** [comment]
@soredake Thanks!

Can you test the latest build here? https://github.com/flathub/md.obsidian.Obsidian/pull/27

**Comment by soredake** [comment]
@joshua-stone yes, it works.
![изображение](https://user-images.githubusercontent.com/5204968/189494150-f51def36-662f-48f1-8906-40d9efebd838.png)

**Comment by joshua-stone** [comment]
Excellent! These changes should be available in a new build soon.
