### ISSUE TITLE
`org.freedesktop.portal.*` permission is not necessary

### ISSUE THREAD

**Issue by bbhtt** [flathub/md.obsidian.Obsidian#281]
### Description

This will be blocked in the linter soon. This issue is a heads-up for that.

See https://github.com/flathub-infra/flatpak-builder-lint/issues/178

### Obsidian Version

```bash session
N/A
```

### Sandbox Permissions

```bash session
N/A
```

### Hardware Information

```bash session
N/A
```

**Comment by joshua-stone** [comment]
@bbhtt Please create an MR to reflect these changes if you have the time.

**Comment by joshua-stone** [comment]
Permission has been removed. Thanks for the info!

**Comment by bbhtt** [comment]
Oh woops I missed the comment, thanks for solving it.
