### ISSUE TITLE
ibus does not work with Obsidian on Flatpak

### ISSUE THREAD

**Issue by vrnavi** [flathub/md.obsidian.Obsidian#317]
### Description

As stated in the title. Specifically, ibus-mozc on Debian 12 (on a Raspberry Pi 5) works outside of Flatpak, and in other Flatpak apps (such as Apostrophe and Text Pieces), but not inside of the Obsidian Flatpak app. I've tried the AppImage which works, the tar.gz which works, and the deb is not an option as Obsidian doesn't give ARM64 deb builds. In practical terms, I am completely unable to type in anything through Ibus' Mozc IME, as Ibus doesn't seem to work on the Flatpak specifically.

### Obsidian Version

```bash session
Obsidian - Markdown-based knowledge base

          ID: md.obsidian.Obsidian
         Ref: app/md.obsidian.Obsidian/aarch64/stable
        Arch: aarch64
      Branch: stable
     Version: 1.5.12
     License: LicenseRef-proprietary=https://obsidian.md/eula
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 650.7 MB
     Runtime: org.freedesktop.Platform/aarch64/23.08
         Sdk: org.freedesktop.Sdk/aarch64/23.08

      Commit: 90cc2d6fbf534568c6074550508e7e415da630b68490780b5014da0…
      Parent: bc9ca2cf7aeed3d5c1bb48ffb9e0d8f46812aa11a274ecbe4182d8b…
     Subject: Update 2 modules (75209143)
        Date: 2024-04-07 17:48:57 +0000
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;
devices=dri;
filesystems=/mnt;xdg-config/gtk-4.0:ro;xdg-run/app/com.discordapp.Discord:create;xdg-run/gnupg:ro;/run/media;home;/media;xdg-config/gtk-3.0:ro;~/.local/share/themes;~/.local/share/fonts:ro;
persistent=~/.ssh;

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_CLEAN_CACHE=1
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
```

### Hardware Information

```bash session
The first command gives me nothing.

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: V3D 7.1 (0xffffffff)
    Version: 23.2.1
    Accelerated: yes
    Video memory: 8044MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.1
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Broadcom
OpenGL renderer string: V3D 7.1
OpenGL core profile version string: 3.1 Mesa 23.2.1-1~bpo12+rpt3
OpenGL core profile shading language version string: 1.40
OpenGL core profile context flags: (none)

OpenGL version string: 3.1 Mesa 23.2.1-1~bpo12+rpt3
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.2.1-1~bpo12+rpt3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

### System Information

```bash session
Running Debian 12 (Raspberry Pi OS Lite from March 15th, 2024), with Gnome 43.9 on Wayland, Flatpak version 1.14.4-1. Ibus in question being version 1.5.27-5.
```

### Logs

```bash session
Debug: Enabling Wayland backend
Deleting cache directory: /home/lapis/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
Debug: Will run Obsidian with the following arguments: --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations
Debug: Additionally, user gave: 
[14:0413/031856.257249:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2024-04-13 07:18:56 Loading main app package /app/resources/obsidian.asar
Updates disabled.
LaunchProcess: failed to execvp:
xdg-settings
[14:0413/031856.756175:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[14:0413/031856.756236:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
close object 1: Invalid argument
close object 2: Invalid argument
close object 3: Invalid argument
close object 1: Invalid argument
close object 2: Invalid argument
close object 3: Invalid argument
close object 1: Invalid argument
close object 2: Invalid argument
close object 3: Invalid argument
```

**Comment by joshua-stone** [comment]
This has been a recurring issue with upstream Electron and flatpak. Please try fcitx5 instead if that's an option.

**Comment by joshua-stone** [comment]
Thanks for testing this out. I've documented this behavior in the README:

https://github.com/flathub/md.obsidian.Obsidian?tab=readme-ov-file#broken-functionality-on-wayland

**Comment by 7HE-W0R1D** [comment]
> I have found a solution to use `fcitx5` with Obsidian on Wayland that has worked for me. I'm running openSUSE Tumbleweed and KDE Plasma 6 (this solution does use Plasma settings that AFAIK aren't as easily available on GNOME)
> 
> 1. Install fcitx5 and set the appropriate environment variables on your system (`GTK_IM_MODULE`, `QT_IM_MODULE`, etc.)
> 2. Restart your system - not sure if this is 100% necessary but it might give Fcitx5 the best shot to load and apply properly.
> 3. Change the `.desktop` entry of Obsidian to add `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime` (the last flag is important)
> 4. Go to System Settings -> Keyboard -> Virtual Keyboard, and select and apply "Fcitx 5 Wayland Launcher".
> 5. Launch Obsidian (from the `.desktop` file) -- Fcitx5 should work now.

Are you using the flatpak version? I cannot seem to get pass the two flags to flatpak, only to the AppImage version.

**Comment by jahinzee** [comment]
> > I have found a solution to use `fcitx5` with Obsidian on Wayland that has worked for me. I'm running openSUSE Tumbleweed and KDE Plasma 6 (this solution does use Plasma settings that AFAIK aren't as easily available on GNOME)
> > 
> > 1. Install fcitx5 and set the appropriate environment variables on your system (`GTK_IM_MODULE`, `QT_IM_MODULE`, etc.)
> > 2. Restart your system - not sure if this is 100% necessary but it might give Fcitx5 the best shot to load and apply properly.
> > 3. Change the `.desktop` entry of Obsidian to add `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime` (the last flag is important)
> > 4. Go to System Settings -> Keyboard -> Virtual Keyboard, and select and apply "Fcitx 5 Wayland Launcher".
> > 5. Launch Obsidian (from the `.desktop` file) -- Fcitx5 should work now.
> 
> Are you using the flatpak version? I cannot seem to get pass the two flags to flatpak, only to the AppImage version.

Yes. Here's what my `.desktop` file for Obsidian looks like for reference (after editing it through KDE's Menu Editor)

```
[Desktop Entry]
Categories=Office;
Comment=Obsidian
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@ --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
Icon=md.obsidian.Obsidian
MimeType=x-scheme-handler/obsidian;
Name=Obsidian
NoDisplay=false
Path=
StartupNotify=true
StartupWMClass=obsidian
Terminal=false
TerminalOptions=
Type=Application
X-Flatpak=md.obsidian.Obsidian
X-Flatpak-Tags=proprietary;
X-KDE-SubstituteUID=false
X-KDE-Username=
```

The relevant flags are at the end of the `Exec=` property on line 4.

**Comment by 7HE-W0R1D** [comment]
> > > I have found a solution to use `fcitx5` with Obsidian on Wayland that has worked for me. I'm running openSUSE Tumbleweed and KDE Plasma 6 (this solution does use Plasma settings that AFAIK aren't as easily available on GNOME)
> > > 
> > > 1. Install fcitx5 and set the appropriate environment variables on your system (`GTK_IM_MODULE`, `QT_IM_MODULE`, etc.)
> > > 2. Restart your system - not sure if this is 100% necessary but it might give Fcitx5 the best shot to load and apply properly.
> > > 3. Change the `.desktop` entry of Obsidian to add `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime` (the last flag is important)
> > > 4. Go to System Settings -> Keyboard -> Virtual Keyboard, and select and apply "Fcitx 5 Wayland Launcher".
> > > 5. Launch Obsidian (from the `.desktop` file) -- Fcitx5 should work now.
> > 
> > 
> > Are you using the flatpak version? I cannot seem to get pass the two flags to flatpak, only to the AppImage version.
> 
> @7HE-W0R1D Yes. Here's what my `.desktop` file for Obsidian looks like for reference (after editing it through KDE's Menu Editor)
> 
> ```
> [Desktop Entry]
> Categories=Office;
> Comment=Obsidian
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@ --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
> Icon=md.obsidian.Obsidian
> MimeType=x-scheme-handler/obsidian;
> Name=Obsidian
> NoDisplay=false
> Path=
> StartupNotify=true
> StartupWMClass=obsidian
> Terminal=false
> TerminalOptions=
> Type=Application
> X-Flatpak=md.obsidian.Obsidian
> X-Flatpak-Tags=proprietary;
> X-KDE-SubstituteUID=false
> X-KDE-Username=
> ```
> 
> The relevant flags are at the end of the `Exec=` property on line 4.
> 
> **EDIT:** Also check that that the Wayland socket for Obsidian is enabled, either through Flatseal, KDE Flatpak settings, or the `flatpak` CLI.

Thanks for the instruction! I put the flags before the `md.obsidian.Obsidian @@u %U @@` and that's probably why its not recognizing. However fcitx is still not working :( I guess its because I'm on GNOME and there're no options for the "Virtual Keyboard" in your step 4.

I'll keep on trying and repost when I find a solution / more insights!

**Comment by KorewaLidesu** [comment]
@7HE-W0R1D
Make sure you have setup Fcitx5 correctly: https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#GNOME
Then put the param accordingly: https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron

**Comment by KorewaLidesu** [comment]
@7HE-W0R1D
```
OS: Arch Linux x86_64
Kernel: Linux 6.10.2-zen1-1-zen
DE: KDE Plasma 6.1.3
WM: KWin (Wayland)
```

`local/obsidian 1.6.7-1`
