### ISSUE TITLE
The git shipped inside Obsidian does not include git-lfs

### ISSUE THREAD

**Issue by lolive** [flathub/md.obsidian.Obsidian#32]
I use Obsidian Git.
It might require git-lfs for some syncs.
Unfortunately git-lfs is not available in the pack.

**Comment by joshua-stone** [comment]
@lolive The latest builds should now use git-lfs

https://github.com/flathub/md.obsidian.Obsidian/commit/045e2e4678c2ea8d9e4d4812b1c64ccefaa4b210
