### ISSUE TITLE
Update the flatpak to only use wayland, with x11 as fallback.

### ISSUE THREAD

**Issue by t3dium** [flathub/md.obsidian.Obsidian#328]
### Additional feature, program, sandbox permission, etc

By default, the obsidian flatpak is configured to only use x11:

![image](https://github.com/flathub/md.obsidian.Obsidian/assets/83690012/dbf3b836-b1f7-42a7-9e09-a6c8c142689d)

I would suggest to change it so that wayland is the default, and for obsidian to fallback to x11 only if wayland is unavailable:

![image](https://github.com/flathub/md.obsidian.Obsidian/assets/83690012/1fae4a1b-a870-44f7-908a-c5799f8430f3)

Wayland offers many benefits over x11: being increased performance, and increased security as other applications are not able to sniff anothers input/output which is possible in xorg. I've tried using obsidian with wayland on my system and it ran without issues:

- Fedora Linux 39 (Workstation Edition)
- Gnome 45
- Tested with amd IGPU, and nvidia (proprietary driver)

As for the "X11 windowing system" permission, it shouldn't really matter whether that is on or off as long as wayland and fallback to x11 are enabled. They both should take precedence over that permission.

**Comment by joshua-stone** [comment]
I agree that Wayland offers many benefits, however I cannot switch the default permission until several blockers are resolved:

https://github.com/flathub/md.obsidian.Obsidian/blob/master/README.md#broken-functionality-on-wayland

**Comment by joshua-stone** [comment]
Closing this issue for now, since enabling Wayland by default has been planned but contingent on documented requirements being met first.
