### ISSUE TITLE
Pen Tablet Not Functional Anymore in Excalidraw Plugin within Obsidian on Wayland (Fedora, Hyprland)

### ISSUE THREAD

**Issue by tratum** [flathub/md.obsidian.Obsidian#345]
***This issue started occurring after 23rd July 2024, and the pen tablet was functioning correctly in Obsidian prior to this date.***

## **System Information**
- Operating System: Fedora Unix Linux
- Window Manager: Hyprland (Wayland)
- Obsidian Installation: Flatpak
- Pen Tablet Model: HUION Tablet_H430P

## **Issue Description**
I am encountering an issue where my HUION Huion Tablet_H430P pen tablet is not functional within the Excalidraw plugin in Obsidian when running on Wayland. Specifically, I am unable to select or draw anything using the pen of my pen tablet within the Excalidraw plugin. However, I am able to use the mouse without any issues. Notably, this issue started occurring after 23rd July 2024, and the pen tablet was functioning correctly in Obsidian prior to this date.

## **Steps to Reproduce**

- Install Obsidian via Flatpak on Fedora Unix Linux with Hyprland (Wayland) as the window manager.
- Open Obsidian and enable the Excalidraw plugin.
- Attempt to use the HUION Huion Tablet_H430P pen tablet within the Excalidraw plugin.

## **Expected Behavior**
I expect to be able to use my pen tablet to draw and interact with elements within the Excalidraw plugin, similar to how it functions with a mouse.

## **Observed Behavior**
The pen tablet is not responsive within the Excalidraw plugin. I am unable to select or draw anything using the pen. However, the pen tablet works correctly in other applications and even in standalone Excalidraw instances outside of Obsidian.

Debugging and Troubleshooting Attempts:

- Verified that the pen tablet works correctly in other applications and standalone Excalidraw.
- Ensured all necessary drivers for the pen tablet are installed and up to date.
- Attempted to run Obsidian with the QT_QPA_PLATFORM=xcb environment variable to force X11 compatibility:
`flatpak run --env=QT_QPA_PLATFORM=xcb md.obsidian.Obsidian`
This did not resolve the issue.
- Verified permissions for Flatpak to access input devices:
`flatpak override md.obsidian.Obsidian --device=all --filesystem=home`
- _**Changed desktop environment from Hyprland to GNOME, but the issue persists in GNOME as well.**_
- Checked system logs and libinput events to ensure the pen tablet is recognized and functioning correctly:
`sudo libinput debug-events`

I would appreciate any guidance or assistance in resolving this issue, as the pen tablet functionality is crucial for my workflow within Obsidian and Excalidraw. Thank you for your support.

### Obsidian Version

```bash session
Obsidian - Markdown-based knowledge base

          ID: md.obsidian.Obsidian
         Ref: app/md.obsidian.Obsidian/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.6.7
     License: LicenseRef-proprietary=https://obsidian.md/eula
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 627.9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: d835343b3ae3b198cb3d42d31e5fb1abb00699211c1e1aab1c506f6490eb9b5a
      Parent: 91c16d530bbd320aef9d7ffc2a6e24b1b57418c4286d07872686acc9d1b0fc2e
     Subject: git: Update git-2.45.2.tar.xz to 2.46.0 (939147bc)
        Date: 2024-07-29 18:01:52 +0000
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=/home/tratum/.themes;/mnt;xdg-run/app/com.discordapp.Discord:create;/home/tratum/.icons;xdg-run/gnupg:ro;/run/media;home;/media;~/.local/share/fonts:ro;
persistent=~/.ssh;

[Environment]
GTK_THEME=WhiteSur-Light
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
OBSIDIAN_CLEAN_CACHE=1
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
ICON_THEME=Flat-Remix-Blue-Light
```

### Hardware Information

```bash session
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f91] (rev a1)
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c1)

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3612 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1650/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 555.58.02
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 555.58.02
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 555.58.02
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### System Information

```bash session
OS: Fedora Linux 40 (Workstation Edition) x86_64 
Host: TUF Gaming FX505DT_FX505DT 1.0 
Kernel: 6.9.11-200.fc40.x86_64 
Packages: 2714 (rpm), 31 (flatpak) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: Hyprland 
WM: sway 
Theme: WhiteSur-Light [GTK2/3] 
Icons: Flat-Remix-Blue-Light [GTK2/3] 
Terminal: kitty 
CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8) @ 2.300GHz 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 2927MiB / 30007MiB
```

### Logs

```bash session
Debug: Enabling Wayland backend
Deleting cache directory: /home/tratum/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
Debug: Will run Obsidian with the following arguments: --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime
Debug: Additionally, user gave: 
[14:0801/223257.497886:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2024-08-01 17:02:57 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
[14:0801/223257.940556:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[14:0801/223257.940689:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2024-08-01 17:02:58 Checking for update using Github
2024-08-01 17:02:59 Success.
2024-08-01 17:02:59 Latest version is 1.6.7
2024-08-01 17:02:59 App is up to date.
```

**Comment by joshua-stone** [comment]
@tratum Passing `--env=QT_QPA_PLATFORM=xcb` doesn't do anything because Obsidian is an Electron application, not a Qt application. You have to disable the Wayland socket in order for it to use XWayland:

```
$ flatpak run --nosocket=wayland --socket=x11 md.obsidian.Obsidian
```


Have you tested the AppImage? Try [downloading the latest release](https://github.com/obsidianmd/obsidian-releases/releases/latest), and see if it does the same thing under Wayland:

```
$ ./Obsidian-1.6.7.AppImage --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime
```

If it's broken under Wayland then you may have to have it fall back under XWayland, especially since the Wayland backend is still experimental.

**Comment by tratum** [comment]
@joshua-stone thank you for the help. I will test it with the AppImage

**Comment by joshua-stone** [comment]
@tratum Please report your findings when you have a moment.

If there's still an issue. then you may want to try rolling back Obsidian:

```
$ sudo flatpak update md.obsidian.Obsidian --commit="0bfbf2dedd198e4748db1e539df04a9d4b9acc29dd31010cd9d0ca22432870ea"
```

If rolling back Obsidian doesn't work, then you may have to also roll back the runtime:
```
$ sudo flatpak update org.freedesktop.Platform//23.08 --commit="1aeabe05e0b2e73715b44957ce19943117a0f4a9201c3612fe095da2333fe77b"
```

**Comment by tratum** [comment]
I have tested using the AppImage and i am still having the same problem

**Comment by tratum** [comment]
> @tratum Please report your findings when you have a moment.
> 
> If there's still an issue. then you may want to try rolling back Obsidian:
> 
> ```
> $ flatpak kill md.obsidian.Obsidian
> $ sudo flatpak update md.obsidian.Obsidian --commit="0bfbf2dedd198e4748db1e539df04a9d4b9acc29dd31010cd9d0ca22432870ea"
> $ flatpak run md.obsidian.Obsidian
> ```
> 
> If rolling back Obsidian doesn't work, then you may have to also roll back the runtime:
> 
> ```
> $ flatpak kill md.obsidian.Obsidian
> $ sudo flatpak update org.freedesktop.Platform//23.08 --commit="1aeabe05e0b2e73715b44957ce19943117a0f4a9201c3612fe095da2333fe77b"
> $ flatpak run md.obsidian.Obsidian
> ```

I have also tried these solutions but i am still facing the Pen Tablet problem

**Comment by joshua-stone** [comment]
@tratum Are there other applications you can use that have tablet support? Maybe try using [Krita](https://krita.org/) and see if it too has issues.

**Comment by RushingAlien** [comment]
This is because Chrome's ozone-wayland backend has yet to support the tablet_v2 protocol. You have to use obsidian with the ozone-x11 backend under xwayland
 
https://issues.chromium.org/issues/40282832  
https://issues.chromium.org/issues/326695622

**Comment by tratum** [comment]
### I am happy to report that i have found a workaround for this bug i encountered and here are the steps we can follow 
- ### _Downgrade the Kernel:_  Downgrade the kernel version to anything below 6.9.12-200.fc40.x86_64 ( I am personally on the kernel version 6.9.11-200.fc40.x86_64)
- ### _Sandbox Permissions:_ Apply the following Sandbox Permissions
  ```
   [Context]
   shared=network;ipc;
   sockets=x11;pulseaudio;fallback-x11;ssh-auth;
   devices=dri;
   filesystems=/home/tratum/.themes;/mnt;xdg-run/app/com.discordapp.Discord:create;/home/tratum/.icons;xdg- 
   run/gnupg:ro;/run/media;home;/media;~/.local/share/fonts:ro;
   persistent=~/.ssh;

   [Environment]
   GTK_THEME=Andromeda-dark
   SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
   OBSIDIAN_ENABLE_AUTOSCROLL=0
   PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
   OBSIDIAN_DISABLE_GPU=0
   GH_PATH=gh
   OBSIDIAN_CLEAN_CACHE=1
   XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
   ICON_THEME=Flat-Remix-Blue-Dark
  ```  


**Note: _Unfortunately This'll not work for wayland and only the x-11-windowing system via the gnome desktop environment_**

Special Thanks to @joshua-stone for helping and co-operating

Additionally would love your advice on where i should report these findings and what should be the necessary steps to resolve this

**Comment by joshua-stone** [comment]
Judging by that output, you need to be have the `x11` socket enabled while having the `wayland` socket disabled. I've documented the README to include this as a Wayland-specific limitation.

**Comment by joshua-stone** [comment]
Hello @tratum , can you check to see if this problem is still happening under Wayland in the latest Obsidian version?

**Comment by jokro7cf** [comment]
> Hello [@tratum](https://github.com/tratum) , can you check to see if this problem is still happening under Wayland in the latest Obsidian version?

@joshua-stone 
Not tratum, but on GNOME i have the same issue. Running the app in XWayland fixes it.

**Comment by laura-olivia-felder** [comment]
If I am not mistaken this (https://chromium-review.googlesource.com/c/chromium/src/+/6666637) should fix the issue once a more current version of electron is used
