### ISSUE TITLE
Build of 1.7.4 is not published

### ISSUE THREAD

**Issue by rombert** [flathub/md.obsidian.Obsidian#365]
### Description

The 1.7.4 changes were merged but not published. Seems there is something wrong with the build - https://buildbot.flathub.org/#/builders/19/builds/19160

### Obsidian Version

```bash session
Not applicable.
```

### Sandbox Permissions

```bash session
Not applicable.
```

### Hardware Information

```bash session
Not applicable.
```

**Comment by rombert** [comment]
This is confusing - I seem to have version 1.7.4 running

![image](https://github.com/user-attachments/assets/ba925305-9517-4f12-a6b2-435cf4c05361)

but the flatpak version is 1.6.7

```
$ flatpak list | grep Obsidian
Obsidian	md.obsidian.Obsidian	1.6.7	stable	system
```

**Comment by jessicarod7** [comment]
I think the Flathub build updates the Obsidian installer, but the app can still update itself. The latest installer is rarely needed to update the main app (this is often the case on Windows). If you go into settings, you'll see this is the case:

![image](https://github.com/user-attachments/assets/e82e0446-bed1-4d55-94ad-734802a8e852)

**Comment by rombert** [comment]
@jessicarod7 - that makes perfect sense, yes. It's the exact state I'm in.

**Comment by joshua-stone** [comment]
A manual rebuild should've fixed it.
