### ISSUE TITLE
The colour theme won't adapt to system

### ISSUE THREAD

**Issue by K4LCIFER** [flathub/md.obsidian.Obsidian#38]
Obsidian wont respond to the system theme (light or dark). The theme only changes if you manually select it from the settings.

Gnome 42.2 Wayland
Arch Linux

**Comment by joshua-stone** [comment]
This is likely to be an upstream issue and isn't unique to the flatpak build:

https://github.com/electron/electron/blob/main/docs/api/native-theme.md

**Comment by xplosionmind** [comment]
Hi @K4LCIFER and @joshua-stone, sorry to ping you, but I am having issues with automatic theme switching, too. Is it still an upstream issue? Were you able to solve this?

Thanks a lot!

**Comment by joshua-stone** [comment]
@xplosionmind It's not an issue that's directly within my control because I only maintain the downstream package. Contact the upstream developers so they can see if rebasing to a newer Electron version fixes this.
