### ISSUE TITLE
arm64 flatpak for Raspberry Pi: now new installer (electron?) in v0.15.8 included

### ISSUE THREAD

**Issue by DerMannAnDerNaht** [flathub/md.obsidian.Obsidian#47]
In Obisidian starting with the new version 0.15.8 on Ubuntu 22.04 on Raspberry Pi (arm64), the app asks for a reinstall as the so called "installer" hasn´t been updatet. I.e. Electron has not been re-included in the package. Could you please consider re-issuing a complete flathub package for Obsidian? Thanks. M

**Comment by joshua-stone** [comment]
This issue should be fixed now.
