### ISSUE TITLE
Git plugin not working

### ISSUE THREAD

**Issue by jalberto** [flathub/md.obsidian.Obsidian#5]
Similar to other flatpack pkg like https://github.com/flathub/com.visualstudio.code/issues/23

upstream issue: https://github.com/denolehov/obsidian-git/issues/22

**Comment by joshua-stone** [comment]
@jalberto I've updated the flatpak to use `ssh-auth`. Please update as such:

```
$ flatpak update md.obsidian.Obsidian
$ flatpak override --reset md.obsidian.Obsidian
$ flatpak run md.obsidian.Obsidian
```

Does the latest update address this issue, or is there more that needs to be done?

**Comment by jalberto** [comment]
thanks @joshua-stone 

Looks like is not yet published in flathub

**Comment by joshua-stone** [comment]
@jalberto Has the permission not been updated yet when checking info?

```
$ flatpak info --show-permissions md.obsidian.Obsidian
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;/mnt;/run/media;
```

**Comment by jalberto** [comment]
The issue is the package has not been updated yet, still in the previous version

`$ flatpak update md.obsidian.Obsidian
Looking for updates…
Nothing to do.`

**Comment by joshua-stone** [comment]
@jalberto I've republished the build. Does it update now?

**Comment by jalberto** [comment]
yes! thanks :)

now the issue is:

`Are you sure you want to continue connecting (yes/no/[fingerprint])?`

so if Obsidian is not run in the console it's impossible to answer that question as it seems unavailable to find `ssh-askpass`

**Comment by joshua-stone** [comment]
Can you describe how it's supposed to behave normally, or how it behaves in the AppImage and/or snap?

If the git plugin is verifying with a brand new host, then I'd hope the git plugin maintainer has provided a built-in mechanism like a confirmation dialog to confirm so Obsidian itself doesn't need to be run from a console. If the git plugin in the flatpak is asking to verify with a previously-verified host yet the AppImage and/or snap don't, then that sounds like a bug unique to the flatpak.

**Comment by jalberto** [comment]
what I can see from the logs is that is trying to run `ssh-askpass` but cannot find it because is outside flatpak, VSC solve this by including its own ssh-askpass.

I just tried the appimage version and it works out of the box (I have not snap in my system)

**Comment by Erick555** [comment]
@jalberto does `/run/user/<UID>/ssh-auth` scoket exist before you launch obsidian flatpak?

**Comment by joshua-stone** [comment]
@jalberto Is there an example repo I can experiment with to test fixes to this bug? I haven't had the time to set up the git plugin.

**Comment by jalberto** [comment]
@joshua-stone without the git-plugin there is not issues, to replicate this you need to install the plugin (using obsidian settings) and initialize a git repo in your obsidian directory. As soon there is a `.git` in the obsidian vault the plugin will try to pull/push

using `--persist=.ssh` doesn't make a difference

@Erick555 `ssh-auth` doesn't' exist, even after running 'ssh-add' or 'ssh-agent' manually

As it seems to work as expected in Appimage I wonder if this is related to isolation and the correct combination or permission is required

**Comment by joshua-stone** [comment]
@jalberto Can you specify more information about the distribution version you're using when running the flatpak and appimage, and whether you're using password authentication and/or key authentication?

I'm running this on Fedora 33, and am having trouble reproducing this behavior. Here's how the git config for my test vault looks:

```
$ cat obsidian-docs/.git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:joshua-stone/obsidian-docs
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
```

I can confirm that it does ask for verifying a fingerprint the first time when doing a push. Subsequent runs don't have this issue though, even if launching from the app menu instead of command line afterward:

```
[jstone@localhost]$ flatpak run md.obsidian.Obsidian 
Gtk-Message: 12:20:16.345: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:20:16.345: Failed to load module "pk-gtk-module"
Gtk-Message: 12:20:16.345: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:20:16.345: Failed to load module "pk-gtk-module"
2020-12-04 17:20:16 Loading main app package /app/resources/obsidian.asar
Updates disabled.

The authenticity of host 'github.com (140.82.114.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
```

And to confirm that ssh-auth creates the known_hosts file needed for subsequent pushes. Before:

```
$ find ~/.ssh
/home/jstone/.ssh
/home/jstone/.ssh/id_rsa
/home/jstone/.ssh/id_rsa.pub
/home/jstone/.ssh/known_hosts.bak
```

After:

```
$ find ~/.ssh
/home/jstone/.ssh
/home/jstone/.ssh/id_rsa
/home/jstone/.ssh/id_rsa.pub
/home/jstone/.ssh/known_hosts.bak
/home/jstone/.ssh/known_hosts
```

**Comment by jalberto** [comment]
@joshua-stone really appreciate the time you are taking to reproduce this :)

I am on Fedora 33 too, and my git config is mostly the same as yours, but using GitLab here (private repository). I am using key authentication protected with a password.
I have others repos in gitlab.com so is even more annoying

I only have this issue with obsidian repo using the flatpack package.
- using git cli in obsidian vault has not issues
- using appimage works

this happens when run twice in a row (last 2 lines if after clicking "close" button in obsidian)

![image](https://user-images.githubusercontent.com/99927/101200697-f6327c80-3666-11eb-87bb-06974e6f9660.png)

**Comment by jalberto** [comment]
I made it work by using `--filesystem=~/.ssh` but I don't know if this is recommended

**Comment by Erick555** [comment]
@jalberto could you show `flatpak info -M md.obsidian.Obsidian`. --filesystem=~/.ssh shouldn't make any difference when app have `--filesystem=home` already.

Also does `printenv SSH_AUTH_SOCK` show anything on your system?

**Comment by jalberto** [comment]
```
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;/mnt;/run/media;
persistent=.ssh;
```

`SSH_AUTH_SOCK -> /run/user/1000/keyring/ssh`

**Comment by joshua-stone** [comment]
@jalberto Are you still experiencing this bug with the latest Obsidian builds?

**Comment by jalberto** [comment]
Sorry for the huge delay, I thought I replied long ago.

Still hitting this, but now in Fedora 34, I need to add `~/.ssh` explicitly to make it work as expected

**Comment by joshua-stone** [comment]
@jalberto Does it work with the latest flatpak build after resetting permissions?
