### ISSUE TITLE
Obsidian v0.15.9 reports an out of date installer on first run

### ISSUE THREAD

**Issue by mdouglass** [flathub/md.obsidian.Obsidian#54]
> To support the latest features and to receive the latest security patches, Obsidian needs a major installer update. You need to manually download and reinstall Obsidian.

Obsidian v0.15.9
Install v0.13.19

From reading at https://forum.obsidian.md/t/unable-to-install-v0-15-8-update/40752/8 it sounds like there is at least a v0.14.x stream of the installer which adds a newer version of Electron.

**Comment by mrickey** [comment]
Thank you for creating a better install for Chromebooks. I wasn't happy with going to the command line every time I wanted to open the appimage install.

Here are a couple of screen shots related to the old installer issue. BTW, I'm experiencing this as well.

![Screenshot 2022-08-20 06 31 57](https://user-images.githubusercontent.com/7904533/185748797-5bc95e60-3a62-4449-9a24-7d17b45c5836.png)
![Screenshot 2022-08-20 06 35 54](https://user-images.githubusercontent.com/7904533/185748803-6e398a77-59d1-44d7-9348-8e1a2bbe7897.png)

Michael

**Comment by joshua-stone** [comment]
This should be fixed now that https://github.com/flathub/md.obsidian.Obsidian/pull/57 has been merged.
