### ISSUE TITLE
Opens new window when using obsidian url

### ISSUE THREAD

**Issue by mikebarkmin** [flathub/md.obsidian.Obsidian#6]
When I am opening an obsidian URL (e.g.: `obsidian://open?vault=vault&file=030%20Persons%20MOC.md`) a new obsidian instance will be launched. It is a bug or desired behavior? I would expect that the current obsidian instance would open the file.

**Comment by joshua-stone** [comment]
@mikebarkmin An update has been pushed that will hopefully address this. Please let me know if you're still experiencing issues.

**Comment by mikebarkmin** [comment]
It works :) Thank you.
