### ISSUE TITLE
Obsidian 1.0

### ISSUE THREAD

**Issue by AdamIsrael** [flathub/md.obsidian.Obsidian#72]
Obsidian 1.0 was [released](https://obsidian.md/1.0). Any chance we'll see the updated version soon?

:heart:

**Comment by joshuag1000** [comment]
its already out on flathub

**Comment by joshuag1000** [comment]
my pr only updates the appdata

**Comment by AdamIsrael** [comment]
On [flathub](https://flathub.org/apps/details/md.obsidian.Obsidian), it currently still lists the latest version as 0.15.9, released July 26, 2022. So, things are moving but it's not generally available yet. 🤷

**Comment by joshuag1000** [comment]
Please look at my PR. It fixes that exact issue.
The app *IS* Updated.
However the person maintaining the repo forgot to update the appdata so the flathub store will show the incorrect version.
Please Update you app then to to the about section and you will see it is on version 1.0.0

**Comment by joshuag1000** [comment]
#71

**Comment by AdamIsrael** [comment]
I see that now. Thank you for the explanation. There's still a _visibility_ issue, but your PR handles that. I'll close this when the PR has been merged.

Thanks!

**Comment by leogout** [comment]
For those of you who came looking for the update you can simply run : 
```
flatpak uninstall md.obsidian.Obsidian
flatpak install md.obsidian.Obsidian
```
This will uninstall the previous version and install the 1.0.0 even though it is mistakenly labelled 0.15.9.
Note that `flatpak update` won't work as the version tag hasn't been updated yet (see #71).

**Comment by joshuag1000** [comment]
> For those of you who came looking for the update you can simply run :
> 
> ```
> flatpak uninstall md.obsidian.Obsidian
> flatpak install md.obsidian.Obsidian
> ```
> 
> This will uninstall the previous version and install the 1.0.0 even though it is mistakenly labelled 0.15.9. Note that `flatpak update` won't work as the version tag hasn't been updated yet (see #71).

Flatpak update *WILL* work. However if you use a GUI to update you app it will say refresh of 0.15.9 instead of update to 1.0.0. Flatpak update WILL pick up the update.

**Comment by joshua-stone** [comment]
> Please look at my PR. It fixes that exact issue. The app _IS_ Updated. However the person maintaining the repo forgot to update the appdata so the flathub store will show the incorrect version. Please Update you app then to to the about section and you will see it is on version 1.0.0

Good catch. What happened was that automatic flathubbot builds were starting to fail:

https://github.com/flathub/md.obsidian.Obsidian/pull/68

The temporary workaround was to delete the offending parameter while updating the Obsidian modules:

https://github.com/flathub/md.obsidian.Obsidian/commit/f662c9b14a45545dd968c7450c203a8bf420401a#diff-1621166159cd3058e65ce146a03c5471d4a9d78a811fe45b1442cfa3bc397d5fL3

While `flatpak run org.flathub.flatpak-external-data-checker md.obsidian.Obsidian.yml  --update --edit-only` did update the sources, the appdata wasn't updated as well, which is typically handled by flathubbot.

**Comment by leogout** [comment]
> Flatpak update _WILL_ work. However if you use a GUI to update you app it will say refresh of 0.15.9 instead of update to 1.0.0. Flatpak update WILL pick up the update.

That is not what happened to me before I came here to write this. `flatpak update` _DID NOT_ update obsidian. Here is my terminal history :
![311907367_2266498410218780_4249498423724519443_n](https://user-images.githubusercontent.com/9843962/196045721-60aa6e32-2b0c-4902-b6af-537446d5e47c.png)

As you can see I had to uninstall and reinstall it. I do not know flatpak very well so I may have misinterpreted the command line outputs.

**Comment by joshua-stone** [comment]
> > Flatpak update _WILL_ work. However if you use a GUI to update you app it will say refresh of 0.15.9 instead of update to 1.0.0. Flatpak update WILL pick up the update.
> 
> That is not what happened to me before I came here to write this. `flatpak update` _DID NOT_ update obsidian. Here is my terminal history : ![311907367_2266498410218780_4249498423724519443_n](https://user-images.githubusercontent.com/9843962/196045721-60aa6e32-2b0c-4902-b6af-537446d5e47c.png)
> 
> As you can see I had to uninstall and reinstall it. I do not know flatpak very well so I may have misinterpreted the command line outputs.

Whatever the case may be, it should be updating normally to the latest change without needing to reinstall:

```
$ flatpak update
Looking for updates…

<snip>

        ID                                               Branch            Op            Remote            Download

 3. [✓] md.obsidian.Obsidian.Locale                      stable            u             flathub             1.5 kB / 3.3 MB

<snip>

12. [✓] md.obsidian.Obsidian                             stable            u             flathub             8.4 kB / 130.7 MB

<snip>
```

```
$ flatpak info md.obsidian.Obsidian

Obsidian - Markdown-based knowledge base

          ID: md.obsidian.Obsidian
         Ref: app/md.obsidian.Obsidian/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.0
     License: LicenseRef-proprietary=https://obsidian.md/eula
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 378.5 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 51c280a8d5e0c818ec1be530df320868b8e77a2068852d9a12a42d0ce6c50406
      Parent: 3468d4d873d465b6829775b1bc8ccf2c8b3fda72653dad1699dc9cb8716a5f16
     Subject: Remove reference of beta from README (ef8799b7)
        Date: 2022-10-16 14:10:00 +0000
```

[Changes from ef8799b7](https://github.com/flathub/md.obsidian.Obsidian/commit/ef8799b7f5353318fdfaaf00feb455bcd64d3c3e)

**Comment by joshuag1000** [comment]
> > Flatpak update _WILL_ work. However if you use a GUI to update you app it will say refresh of 0.15.9 instead of update to 1.0.0. Flatpak update WILL pick up the update.
> 
> That is not what happened to me before I came here to write this. `flatpak update` _DID NOT_ update obsidian. Here is my terminal history : ![311907367_2266498410218780_4249498423724519443_n](https://user-images.githubusercontent.com/9843962/196045721-60aa6e32-2b0c-4902-b6af-537446d5e47c.png)
> 
> As you can see I had to uninstall and reinstall it. I do not know flatpak very well so I may have misinterpreted the command line outputs.

It doesn't really matter now as it is fixed.
I suspect you updated before without realizing hence why it shows no updates. I maintain an app on flathub so i know that you dont need up update the appdata for an update to be pushed. when you initially did flatpak update did you actually open obsidian and check its version?

**Comment by leogout** [comment]
You are right it does not matter now that it is fixed, thanks for taking the time to answer anyway. I've checked before and there was no tabs (1.0.0 introduces tabs) so I'm pretty sure it was on 0.15.9... It is weird but unimportant, thanks for your great work and reactivity, have a nice day.

**Comment by joshua-stone** [comment]
> > > Flatpak update _WILL_ work. However if you use a GUI to update you app it will say refresh of 0.15.9 instead of update to 1.0.0. Flatpak update WILL pick up the update.
> > 
> > 
> > That is not what happened to me before I came here to write this. `flatpak update` _DID NOT_ update obsidian. Here is my terminal history : IMAGE REMOVED FROM REPLY TO KEEP THREAD CLEAN
> > As you can see I had to uninstall and reinstall it. I do not know flatpak very well so I may have misinterpreted the command line outputs.
> 
> It doesn't really matter now as it is fixed. I suspect you updated before without realizing hence why it shows no updates. I maintain an app on flathub so i know that you dont need up update the appdata for an update to be pushed. when you initially did flatpak update did you actually open obsidian and check its version?

Yes, I updated Obsidian before this issue was opened. Obsidian also didn't have internet access so it wouldn't be able to use its built-in updater to fetch a new ASAR build. The version in the app was updated to 1.0 as expected, so the only discrepancy would've been in the appdata shown on flathub.
