### ISSUE TITLE
Installation doesn´t work

### ISSUE THREAD

**Issue by trujedu** [flathub/md.obsidian.Obsidian#88]
Trying to install the snap version in KDE Neon Linux, using the command
   snap install obsidian_1.0.3_amd64.snap

I am getting the following message:
   error: cannot find signatures with metadata for snap

**Comment by joshua-stone** [comment]
@trujedu This is the issue tracker for the [Obsidian flatpak](https://flathub.org/apps/details/md.obsidian.Obsidian), so any support questions should be directed to the [support forum](https://forum.obsidian.md/c/get-help/19)

 [KDE Neon appears to have flatpak preconfigured](https://flatpak.org/setup/KDE%20neon), so you can install the Obsidian flatpak like this:

```bash
$ flatpak install md.obsidian.Obsidian
$ flatpak run md.obsidian.Obsidian
```
