### ISSUE TITLE
Obsidian shows a black window upon launch without loading icons

### ISSUE THREAD

**Issue by Horuyuki** [flathub/md.obsidian.Obsidian#90]
- Fedora 37 Silverblue, Gnome 43.2, Wayland
- Flatpak installation version `1.0.3`

Behavior:
1. Launch app
2. Black window appears
3. Takes a long time to load, but does not show the usual gray loading background and animation

Made sure to update flatpak before posing.

**Comment by joshua-stone** [comment]
Does this happen with other versions of Obsidian, like the Appimage or tarball? Are you running under XWayland or [native Wayland](https://github.com/flathub/md.obsidian.Obsidian#wayland-support)?

**Comment by Horuyuki** [comment]
I do not know what Fedora 37 used. What I know is my installation is vanilla, so no changes made.
Appimage works perfectly fine.

**Comment by joshua-stone** [comment]
Do you have more information on your system, and do you have a screenshot? What is your hardware setup like?

**Comment by Horuyuki** [comment]
Screenshot of Obsidian upon launch: https://imgur.com/a/b7BGByO
GPU: Nvidia 980Ti
CPU: intel i7 6th gen

**Comment by joshua-stone** [comment]
Which Nvidia driver version are you using? Please show info of the following:

```
$ glxinfo | grep OpenGL
$ flatpak list --runtime | grep nvidia
```

**Comment by Horuyuki** [comment]
```
$ glxinfo | grep OpenGL
OpenGL vendor string: nouveau
OpenGL renderer string: NV120
OpenGL core profile version string: 4.3 (Core Profile) Mesa 22.2.3
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.3 (Compatibility Profile) Mesa 22.2.3
OpenGL shading language version string: 4.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```
`flatpak list --runtime | grep nvidia` yields nothing.

**Comment by joshua-stone** [comment]
Nouveau appears to cause many Chromium/Electron issues in flatpak:

https://github.com/search?q=org%3Aflathub+nouveau&type=issues

Tracking down the exact might not be straightforward since Nouveau doesn't get tested as much as the Nvidia driver. I think there are several options you can try:

1) Try to launch Obsidian without GPU acceleration

```
$ flatpak run md.obsidian.Obsidian --disable-gpu
```

2) Launch Obsidian with the Wayland backend:

```
$ flatpak run --env=OBSIDIAN_USE_WAYLAND=1 md.obsidian.Obsidian
```

3) Launch Gnome Shell under Xorg instead of Wayland:

```
$ echo $XDG_SESSION_TYPE
x11
$ flatpak run --env=OBSIDIAN_USE_WAYLAND=0 md.obsidian.Obsidian
```
4) If none of the above work, then installing the Nvidia driver might be your best option:

https://rpmfusion.org/Howto/NVIDIA

**Comment by Horuyuki** [comment]
It runs perfect by disabling gpu.

**Comment by joshua-stone** [comment]
@Horuyuki [A workaround has been added](https://github.com/flathub/md.obsidian.Obsidian#gpu-acceleration):

```
$ flatpak update md.obsidian.Obsidian
$ flatpak run --env=OBSIDIAN_DISABLE_GPU=1 md.obsidian.Obsidian
```

You should see `Debug: Will run Obsidian with the following arguments: --disable-gpu` in the output.

If that works, then you should be able set a permanent workaround:

```
$ flatpak override --user --env=OBSIDIAN_DISABLE_GPU=1 md.obsidian.Obsidian
```
```

**Comment by Horuyuki** [comment]
I installed the `akmod-nvidia` Fedora package, rebooted. Then updated Obsidian and overrode the settings per your instructions.

Not only does it start normally, it feels twice as fast.

I don't know if graph view (I don't usually use) will suffer without a gpu, but hey, it is faster for now.

**Comment by joshua-stone** [comment]
Fantastic! Marking as closed.
