### ISSUE TITLE
Community Plugins and Themes cannot be accessed

### ISSUE THREAD

**Issue by Zsbyqx20** [flathub/md.obsidian.Obsidian#95]
I cannot access community plug-ins or themes since the update? (I'm not sure) It just showed that "cannot load", but the app-image version seems fine till now. Is this a bug or is this my bug? hope for the update & solution ^.^

**Comment by joshua-stone** [comment]
@Zsbyqx20 To clarify, this is encountered in the appimage and not the flatpak? If so, then please direct your issue to the [Obsidian forum](https://forum.obsidian.md/c/get-help/19) since this is the issue tracker for the flatpak.

**Comment by lishid** [comment]
We've gotten reports that some countries have been blocking GitHub from being accessed - Try setting your computer's DNS setting to Google's 8.8.8.8 or CloudFlare's 1.1.1.1, we've heard some people resolved their issues by doing that.

**Comment by Zsbyqx20** [comment]
@lishid I'm wondering that whether the appimage version and the flatpak version are using different internet settings? 
I can access the community **without any problem** by using the app-image downloaded in the [Obsidian website](https://obsidian.md/) , but I **can't do so** when using the flatpak... so I didn't consider it was network settings that matter. Or is it possible to manually set an proxy for the flatpak?

**Comment by lishid** [comment]
Ok if the AppImage works then it's definitely some permission issue you're running into with how you have flatpak setup. I'm not a Linux user so I don't really have more experience from here on.

**Comment by joshua-stone** [comment]
[I'm not sure why the community plugins would be inaccessible when network access has been given specifically for downloading plugins](https://github.com/flathub/md.obsidian.Obsidian/blob/12cf75b1c97569d777760d5a788eb8cc224a770c/md.obsidian.Obsidian.yml#L27). Do you have more information about your system, such as the distribution, release, flatpak version, desktop environment, etc?

Make sure that the network permission was set correctly and hostnames are reachable:

```
$ flatpak info --show-permissions md.obsidian.Obsidian
$ flatpak run --command=getent md.obsidian.Obsidian hosts github.com obsidian.md
```

Also, try downloading the list of plugins manually:

```
$ flatpak run --command=curl md.obsidian.Obsidian https://raw.githubusercontent.com/obsidianmd/obsidian-releases/master/community-plugins.json
```

**Comment by Zsbyqx20** [comment]
@joshua-stone hello! thank you for your guidance in time! I tried the command you provided and the result is below; It's a pity that I cannot understand the result well, so would you please help me check is there something wrong indeed? Anyway, I still cannot access the community, while downloading manually is fine.

the result for `$ flatpak info --show-permissions md.obsidian.Obsidian` is :
```bash
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
OBSIDIAN_DISABLE_GPU_SANDBOX=0
OBSIDIAN_USE_WAYLAND=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
```

the result for `flatpak run --command=getent md.obsidian.Obsidian hosts github.com obsidian.md` is:
```bash
20.205.243.166  github.com
2606:4700:3036::ac43:c673 obsidian.md
2606:4700:3036::6815:44cb obsidian.md
```

Thank you again for your help! 😃

**Comment by joshua-stone** [comment]
@Zsbyqx20 Those results don't look out of place, so I'm not sure whether it's necessarily an issue within the flatpak environment itself.

I wonder if there's an issue within your Obsidian configuration. Can you see how a first-run of Obsidian would behave, and can you show screenshots?

```
$ # Make sure Obsidian isn't running 
$ flatpak kill md.obsidian.Obsidian
$ # Make sure Obsidian is up to date
$ flatpak update md.obsidian.Obsidian
$ # Temporarily move Obsidian data folder
$ mv ~/.var/app/md.obsidian.Obsidian ~/.var/app/md.obsidian.Obsidian.bak
$ # Now run Obsidian with a clean slate
$ flatpak run md.obsidian.Obsidian
$ # When done, move folder back
$ rm -rf ~/.var/app/md.obsidian.Obsidian
$ mv ~/.var/app/md.obsidian.Obsidian.bak ~/.var/app/md.obsidian.Obsidian
```

**Comment by Zsbyqx20** [comment]
@joshua-stone I have run these commands and it seems there is indeed a problem, which is called `net::ERR_CONNECTION_REFUSED`. and the whole output is below:
```bash
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
2022-12-20 07:13:26 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 15:13:26.368: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:13:26.368: Failed to load module "pk-gtk-module"
Gtk-Message: 15:13:26.368: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:13:26.368: Failed to load module "pk-gtk-module"
[13:1220/151326.377834:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: 没有那个文件或目录
[13:1220/151326.377864:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: 没有那个文件或目录
2022-12-20 07:13:26 Checking for update using Github
2022-12-20 07:13:26 Failed to check for update using Github (net::ERR_CONNECTION_REFUSED)
Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
2022-12-20 07:13:26 Checking for update using obsidian.md
2022-12-20 07:13:29 Success.
2022-12-20 07:13:29 Latest version is 1.0.3
2022-12-20 07:13:29 App is up to date.
```
So what had caused this to happen? I guess it might be related to electron since the `SimpleURLLoaderWrapper` it gives?
Whatever, it must be the network configuration problem.

**Comment by joshua-stone** [comment]
@Zsbyqx20 I have filed a bug on it here:

https://github.com/flathub/org.electronjs.Electron2.BaseApp/issues/38

Can you file a bug report on flatpak's issue tracker here? I cannot fill it out on my own because I don't have sufficient information about your system

https://github.com/flatpak/flatpak/issues/new/choose

**Comment by Zsbyqx20** [comment]
@joshua-stone thanks a lot! And I've learned a lot from u. I'll give it a try :)

**Comment by joshua-stone** [comment]
@Zsbyqx20 I've filed a bug report here:

https://github.com/refi64/zypak/issues/27

I think you should file a bug report in [flatpak's upstream issue tracker](https://github.com/flatpak/flatpak/issues) to increase our chances of fixing this issue.

**Comment by Bananaman** [comment]
I am on Fedora 37. Obsidian flatpak works perfectly here. I can download themes and plugins within the app. Just to let you know that this issue definitely doesn't affect me.

**Comment by joshua-stone** [comment]
Thank you @Bananaman!

I'm going to close this issue since it'd been difficult to replicate and is likely not intrinsic to the Obsidian flatpak or even in zypak.
