### ISSUE TITLE
ChromeOS unbound variable error

### ISSUE THREAD

**Issue by hovo1990** [flathub/md.obsidian.Obsidian#97]
Hello,

Running with the newest update of obsidian on ChromeOS Linux environment gives the following error:

`johngra1990@penguin:~$ flatpak run md.obsidian.Obsidian
/app/bin/obsidian.sh: line 22: XDG_SESSION_TYPE: unbound variable`

Updating with an older build makes obsidian work again.
flatpak update --commit=267678d32278740230e88aeb7966a45ab792f765f50d0a6f63bb130fa1339e45 md.obsidian.Obsidian

How can I fix it?

**Comment by michaelsmanley** [comment]
Having the same issue. ChromeOS Version 108.0.5359.111 (Official Build) (64-bit), Obdisian update installed by CLI.

**Comment by joshua-stone** [comment]
@hovo1990 @michaelsmanley The launch script will exit early if there are unset variables:

https://github.com/flathub/md.obsidian.Obsidian/blob/master/obsidian.sh#L3

Can you see what happens when setting `XDG_SESSION_TYPE` with the latest build?

```
$ flatpak update md.obsidian.Obsidian
$ flatpak run --env=XDG_SESSION_TYPE=wayland md.obsidian.Obsidian
$ flatpak run --env=XDG_SESSION_TYPE=x11 md.obsidian.Obsidian
```

Also, can you see whether there's anything in the sandbox that would help the launcher script determine the session type?

```
$ flatpak run --command=env md.obsidian.Obsidian | grep -i 'x11\|wayland'
```

This is what what I have for comparison:

```
$ flatpak run --command=env md.obsidian.Obsidian | grep -i 'x11\|wayland'
OBSIDIAN_USE_WAYLAND=1
WAYLAND_DISPLAY=wayland-0
XDG_SESSION_TYPE=wayland
```

**Comment by hovo1990** [comment]
So I updated to the latest build.

1. Running obsidian with either command works fine. 

`$ flatpak run --env=XDG_SESSION_TYPE=wayland md.obsidian.Obsidian`
or 
`$ flatpak run --env=XDG_SESSION_TYPE=x11 md.obsidian.Obsidian
`
2. Running command:
`flatpak run --command=env md.obsidian.Obsidian | grep -i 'x11\|wayland`

Gives the following output:
```
$ flatpak run --command=env md.obsidian.Obsidian | grep -i 'x11\|wayland'
WAYLAND_DISPLAY_LOW_DENSITY=wayland-1
WAYLAND_DISPLAY=wayland-0
OBSIDIAN_USE_WAYLAND=0
```

3. Simply trying to run through the start menu shows nothing.
4. If running the following command, get this error:
```
$ flatpak run md.obsidian.Obsidian
/app/bin/obsidian.sh: line 22: XDG_SESSION_TYPE: unbound variable
```

Thank you for the help, at least these two commands work :
$ flatpak run --env=XDG_SESSION_TYPE=wayland md.obsidian.Obsidian
$ flatpak run --env=XDG_SESSION_TYPE=x11 md.obsidian.Obsidian

**Comment by joshua-stone** [comment]
@hovo1990 @michaelsmanley I have some changes ready for testing:

https://github.com/flathub/md.obsidian.Obsidian/pull/98

Can you test this fix?

```
$ flatpak install --user https://dl.flathub.org/build-repo/125418/md.obsidian.Obsidian.flatpakref
$ flatpak run --user md.obsidian.Obsidian//test
```

**Comment by hovo1990** [comment]
Tried and ran it. The application launched.

```
$ flatpak install --user https://dl.flathub.org/build-repo/125418/md.obsidian.Obsidian.flatpakref
$ flatpak run --user md.obsidian.Obsidian//test
```

**Comment by joshua-stone** [comment]
@hovo1990 The fix has been merged and deployed.

```
$ flatpak uninstall --user md.obsidian.Obsidian//test
$ flatpak install md.obsidian.Obsidian
$ flatpak run md.obsidian.Obsidian//test
```
