### ISSUE TITLE
Obsidian won't run on ChromeOS

### ISSUE THREAD

**Issue by knowtheory** [flathub/md.obsidian.Obsidian#99]
Hey there,

I installed flatpak specifically to manage my Obsidian installation a couple months ago.  The most recent update of Obsidian broke my Obsidian installation, and i did a bunch of uninstalling / reinstalling to see if that'd fix it.

Regardless of what I did, trying to `run` obsidian would bomb out with a message that `XDG_SESSION_TYPE` was unset:

```
/app/bin/obsidian.sh: line 22: "xdg_session_type" : unbound variable
```

After a whole bunch of googling, and the note about Flatseal in release notes, i ended up just setting `XDG_SESSION_TYPE` to `wayland` and `OBSIDIAN_USE_WAYLAND` to `1`, and that's allowed me to keep rolling.

**Comment by knowtheory** [comment]
If i knew more about flatpak & wayland here, i'd offer a patch, but i'm afraid i'm out of my depth and just wanted to give y'all a heads up / leave a record for others to find!

**Comment by joshua-stone** [comment]
@knowtheory This appears to be a duplicate of another issue:

https://github.com/flathub/md.obsidian.Obsidian/issues/97

It should already be fixed if you update to the latest build:

```
$ flatpak update md.obsidian.Obsidian
$ flatpak run md.obsidian.Obsidian
```

**Comment by knowtheory** [comment]
Great thanks!

**Comment by joshua-stone** [comment]
@knowtheory Are you able to run it now?

**Comment by joshua-stone** [comment]
Marking as closed as the issue should already be fixed on ChromeOS.
